SpECTRE: src/Domain/BlockNeighbor.hpp File Reference
BlockNeighbor.hpp File Reference
Defines class template BlockNeighbor.
#include <iosfwd>
#include <pup.h>
#include "Domain/Direction.hpp"
#include "Domain/Orientation.hpp"
Classes
class BlockNeighbor< VolumeDim >
Information about the neighbor of a Block in a particular direction.
Functions
template<size_t VolumeDim>
std::ostream & operator<< (std::ostream &os, const BlockNeighbor< VolumeDim > &block_neighbor)
Output operator for BlockNeighbor.
template<size_t VolumeDim>
bool operator== (const BlockNeighbor< VolumeDim > &lhs, const BlockNeighbor< VolumeDim > &rhs) noexcept
template<size_t VolumeDim>
bool operator!= (const BlockNeighbor< VolumeDim > &lhs, const BlockNeighbor< VolumeDim > &rhs) noexcept
Detailed Description
Defines class template BlockNeighbor.
Function Documentation
operator!=()
template<size_t VolumeDim> bool operator!= (const BlockNeighbor< VolumeDim > & lhs, const BlockNeighbor< VolumeDim > & rhs) noexcept
References operator!=(), and operator==().
Referenced by operator!=(), and BlockNeighbor< VolumeDim >::orientation().
operator<<()
template<size_t VolumeDim> std::ostream& operator<< (std::ostream & os, const BlockNeighbor< VolumeDim > & block_neighbor)
Output operator for BlockNeighbor.
References BlockNeighbor< VolumeDim >::id(), and BlockNeighbor< VolumeDim >::orientation().
Referenced by BlockNeighbor< VolumeDim >::orientation().
operator==()
template<size_t VolumeDim> bool operator== (const BlockNeighbor< VolumeDim > & lhs, const BlockNeighbor< VolumeDim > & rhs) noexcept
Referenced by operator!=(), and BlockNeighbor< VolumeDim >::orientation().