SpECTRE: src/Domain/Block.cpp File Reference
Block.cpp File Reference
#include "Domain/Block.hpp"
#include <ostream>
#include "Utilities/StdHelpers.hpp"
Functions
template<size_t VolumeDim>
std::ostream & operator<< (std::ostream &os, const Block< VolumeDim > &block)
template<size_t VolumeDim>
bool operator== (const Block< VolumeDim > &lhs, const Block< VolumeDim > &rhs) noexcept
template<size_t VolumeDim>
bool operator!= (const Block< VolumeDim > &lhs, const Block< VolumeDim > &rhs) noexcept
template std::ostream & operator<< (std::ostream &, const Block< 1 > &)
template std::ostream & operator<< (std::ostream &, const Block< 2 > &)
template std::ostream & operator<< (std::ostream &, const Block< 3 > &)
template bool operator== (const Block< 1 > &, const Block< 1 > &)
template bool operator== (const Block< 2 > &, const Block< 2 > &)
template bool operator== (const Block< 3 > &, const Block< 3 > &)
template bool operator!= (const Block< 1 > &, const Block< 1 > &)
template bool operator!= (const Block< 2 > &, const Block< 2 > &)
template bool operator!= (const Block< 3 > &, const Block< 3 > &)
Function Documentation
operator!=() [1/4]
template<size_t VolumeDim> bool operator!= (const Block< VolumeDim > & lhs, const Block< VolumeDim > & rhs) noexcept
References operator!=(), and operator==().
Referenced by Block< VolumeDim >::external_boundaries(), and operator!=().
operator!=() [2/4]
template bool operator!= (const Block< 1 > & , const Block< 1 > &)
operator!=() [3/4]
template bool operator!= (const Block< 2 > & , const Block< 2 > &)
operator!=() [4/4]
template bool operator!= (const Block< 3 > & , const Block< 3 > &)
operator<<() [1/4]
template<size_t VolumeDim> std::ostream& operator<< (std::ostream & os, const Block< VolumeDim > & block)
operator<<() [2/4]
template std::ostream& operator<< (std::ostream & , const Block< 1 > &)
operator<<() [3/4]
template std::ostream& operator<< (std::ostream & , const Block< 2 > &)
operator<<() [4/4]
template std::ostream& operator<< (std::ostream & , const Block< 3 > &)
operator==() [1/4]
template<size_t VolumeDim> bool operator== (const Block< VolumeDim > & lhs, const Block< VolumeDim > & rhs) noexcept
Referenced by Block< VolumeDim >::external_boundaries(), and operator!=().
operator==() [2/4]
template bool operator== (const Block< 1 > & , const Block< 1 > &)
operator==() [3/4]
template bool operator== (const Block< 2 > & , const Block< 2 > &)
operator==() [4/4]
template bool operator== (const Block< 3 > & , const Block< 3 > &)