SpECTRE: Slab Class Reference
Slab Class Reference
Time
A chunk of time. Every element must reach slab boundaries exactly, no matter how it actually takes time steps to get there. The simulation can only be assumed to have global data available at slab boundaries.
#include <Slab.hpp>
Public Member Functions
Slab () noexcept
Default constructor gives an invalid Slab.
Slab (double start, double end) noexcept
Construct a slab running between two times (exactly).
Time start () const noexcept
Time end () const noexcept
TimeDelta duration () const noexcept
Slab advance () const noexcept
Create a new slab immediately following this one with the same (up to roundoff) duration.
Slab retreat () const noexcept
Create a new slab immediately preceeding this one with the same (up to roundoff) duration.
Slab advance_towards (const TimeDelta &dt) const noexcept
Create a slab adjacent to this one in the direction indicated by the argument, as with advance() or retreat().
Slab with_duration_from_start (double duration) const noexcept
Create a new slab with the same start time as this one with the given duration (up to roundoff).
Slab with_duration_to_end (double duration) const noexcept
Create a new slab with the same end time as this one with the given duration (up to roundoff).
bool is_followed_by (const Slab &other) const noexcept
Check if this slab is immediately followed by the other slab.
bool is_preceeded_by (const Slab &other) const noexcept
Check if this slab is immediately preceeded by the other slab.
void pup (PUP::er &p) noexcept
Static Public Member Functions
static Slab with_duration_from_start (double start, double duration) noexcept
Construct a slab with a given start time and duration. The actual duration may differ by roundoff from the supplied value.
static Slab with_duration_to_end (double end, double duration) noexcept
Construct a slab with a given end time and duration. The actual duration may differ by roundoff from the supplied value.
Friends
class Time
class TimeDelta
bool operator== (const Slab &a, const Slab &b) noexcept
bool operator< (const Slab &a, const Slab &b) noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
bool operator== (const Time &a, const Time &b) noexcept
Detailed Description
A chunk of time. Every element must reach slab boundaries exactly, no matter how it actually takes time steps to get there. The simulation can only be assumed to have global data available at slab boundaries.
Constructor & Destructor Documentation
Slab() [1/2]
Slab::Slab () inline noexcept
Default constructor gives an invalid Slab.
Slab() [2/2]
Slab::Slab (double start, double end) inline noexcept
Construct a slab running between two times (exactly).
References ASSERT.
Member Function Documentation
advance()
Slab Slab::advance () const inline noexcept
Create a new slab immediately following this one with the same (up to roundoff) duration.
Referenced by advance_towards(), and integrate_variable_test().
advance_towards()
Slab Slab::advance_towards (const TimeDelta & dt) const noexcept
Create a slab adjacent to this one in the direction indicated by the argument, as with advance() or retreat().
References advance(), ASSERT, and retreat().
duration()
TimeDelta Slab::duration () const noexcept
References TimeDelta.
Referenced by integrate_test(), integrate_variable_test(), stability_test(), and Time::value().
end()
Time Slab::end () const noexcept
References Time.
Referenced by integrate_test(), and integrate_variable_test().
is_followed_by()
bool Slab::is_followed_by (const Slab & other) const inline noexcept
Check if this slab is immediately followed by the other slab.
Referenced by is_preceeded_by().
is_preceeded_by()
bool Slab::is_preceeded_by (const Slab & other) const inline noexcept
Check if this slab is immediately preceeded by the other slab.
References is_followed_by().
pup()
void Slab::pup (PUP::er & p) noexcept
retreat()
Slab Slab::retreat () const inline noexcept
Create a new slab immediately preceeding this one with the same (up to roundoff) duration.
Referenced by advance_towards().
start()
Time Slab::start () const noexcept
References Time.
Referenced by integrate_test(), and stability_test().
with_duration_from_start() [1/2]
static Slab Slab::with_duration_from_start (double start, double duration) inline static noexcept
Construct a slab with a given start time and duration. The actual duration may differ by roundoff from the supplied value.
Referenced by integrate_test(), integrate_variable_test(), and stability_test().
with_duration_from_start() [2/2]
Slab Slab::with_duration_from_start (double duration) const inline noexcept
Create a new slab with the same start time as this one with the given duration (up to roundoff).
with_duration_to_end() [1/2]
static Slab Slab::with_duration_to_end (double end, double duration) inline static noexcept
Construct a slab with a given end time and duration. The actual duration may differ by roundoff from the supplied value.
Referenced by integrate_test(), and integrate_variable_test().
with_duration_to_end() [2/2]
Slab Slab::with_duration_to_end (double duration) const inline noexcept
Create a new slab with the same end time as this one with the given duration (up to roundoff).
Friends And Related Function Documentation
operator<
bool operator< (const Slab & a, const Slab & b) friend
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
operator== [1/2]
bool operator== (const Slab & a, const Slab & b) friend
operator== [2/2]
bool operator== (const Time & a, const Time & b) friend
Time
friend class Time friend
Referenced by end(), and start().
TimeDelta
friend class TimeDelta friend
Referenced by duration().
The documentation for this class was generated from the following files:
src/Time/Slab.hpp
src/Time/Slab.cpp