SpECTRE: CoordinateMap< SourceFrame, TargetFrame, Maps > Class Template Reference
CoordinateMap< SourceFrame, TargetFrame, Maps > Class Template Reference
Computational Domain | Coordinate Maps
A coordinate map or composition of coordinate maps.
#include <CoordinateMap.hpp>
Public Types
using source_frame = SourceFrame
using target_frame = TargetFrame
using maps_list = tmpl::list< Maps... >
Public Member Functions
CoordinateMap ()=default
Used for Charm++ serialization.
constexpr CoordinateMap (Maps... maps)
template<typename T >
constexpr tnsr::I< T, dim, TargetFrame > operator() (const tnsr::I< T, dim, SourceFrame > &source_point) const
Apply the Maps... to the point(s) source_point
template<typename T >
constexpr tnsr::I< T, dim, SourceFrame > inverse (const tnsr::I< T, dim, TargetFrame > &target_point) const
Apply the inverse Maps... to the point(s) target_point
template<typename T >
constexpr Tensor< T, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, SourceFrame >, SpatialIndex< dim, UpLo::Lo, TargetFrame > > > inv_jacobian (const tnsr::I< T, dim, SourceFrame > &source_point) const
Compute the inverse Jacobian of the Maps... at the point(s) source_point
template<typename T >
constexpr Tensor< T, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, TargetFrame >, SpatialIndex< dim, UpLo::Lo, SourceFrame > > > jacobian (const tnsr::I< T, dim, SourceFrame > &source_point) const
Compute the Jacobian of the Maps... at the point(s) source_point
void pup (PUP::er &p)
template<typename T >
constexpr tnsr::I< T, CoordinateMap< SourceFrame, TargetFrame, Maps... >::dim, TargetFrame > operator() (const tnsr::I< T, dim, SourceFrame > &source_point) const
template<typename T >
constexpr tnsr::I< T, CoordinateMap< SourceFrame, TargetFrame, Maps... >::dim, SourceFrame > inverse (const tnsr::I< T, dim, TargetFrame > &target_point) const
template<typename T >
constexpr auto inv_jacobian (const tnsr::I< T, dim, SourceFrame > &source_point) const -> Tensor< T, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, SourceFrame >, SpatialIndex< dim, UpLo::Lo, TargetFrame >>>
template<typename T >
constexpr auto jacobian (const tnsr::I< T, dim, SourceFrame > &source_point) const -> Tensor< T, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< dim, UpLo::Up, TargetFrame >, SpatialIndex< dim, UpLo::Lo, SourceFrame >>>
Static Public Attributes
static constexpr size_t dim = CoordinateMaps::map_dim<Maps...>
Friends
bool operator== (const CoordinateMap &lhs, const CoordinateMap &rhs) noexcept
Detailed Description
template<typename SourceFrame, typename TargetFrame, typename... Maps>
class CoordinateMap< SourceFrame, TargetFrame, Maps >
A coordinate map or composition of coordinate maps.
Maps coordinates from the SourceFrame to the TargetFrame using the coordinate maps Maps.... The individual maps are applied left to right from the source to the target Frame. The inverse map, as well as Jacobian and inverse Jacobian are also provided. The CoordinateMap class must be used even if just wrapping a single coordinate map. It is designed to be an extremely minimal interface to the underlying coordinate maps. For a list of all coordinate maps see the CoordinateMaps group or namespace.
Each coordinate map must contain a static constexpr size_t dim variable that is equal to the dimensionality of the map. The Coordinatemap class contains a member static constexpr size_t dim, a type alias source_frame, a type alias target_frame and typelist of theMaps...`.
Member Typedef Documentation
maps_list
template<typename SourceFrame, typename TargetFrame, typename... Maps> using CoordinateMap< SourceFrame, TargetFrame, Maps >::maps_list = tmpl::list<Maps...>
source_frame
template<typename SourceFrame, typename TargetFrame, typename... Maps> using CoordinateMap< SourceFrame, TargetFrame, Maps >::source_frame = SourceFrame
target_frame
template<typename SourceFrame, typename TargetFrame, typename... Maps> using CoordinateMap< SourceFrame, TargetFrame, Maps >::target_frame = TargetFrame
Constructor & Destructor Documentation
CoordinateMap() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap () default
Used for Charm++ serialization.
CoordinateMap() [2/2]
template<typename SourceFrame , typename TargetFrame , typename... Maps> constexpr CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap (Maps... maps) explicit
References CoordinateMap< SourceFrame, TargetFrame, Maps >::dim.
Member Function Documentation
inv_jacobian() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr Tensor<T, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, SourceFrame>, SpatialIndex<dim, UpLo::Lo, TargetFrame> > > CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian (const tnsr::I< T, dim, SourceFrame > & source_point) const
Compute the inverse Jacobian of the Maps... at the point(s) source_point
inv_jacobian() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr auto CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian (const tnsr::I< T, dim, SourceFrame > & source_point) const -> Tensor<T, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, SourceFrame>, SpatialIndex<dim, UpLo::Lo, TargetFrame>>>
References gsl::at(), CoordinateMap< SourceFrame, TargetFrame, Maps >::dim, LIKELY, and tuple_transform().
inverse() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr tnsr::I<T, dim, SourceFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::inverse (const tnsr::I< T, dim, TargetFrame > & target_point) const
Apply the inverse Maps... to the point(s) target_point
inverse() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr tnsr::I<T, CoordinateMap<SourceFrame, TargetFrame, Maps...>::dim, SourceFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::inverse (const tnsr::I< T, dim, TargetFrame > & target_point) const
jacobian() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr Tensor<T, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, TargetFrame>, SpatialIndex<dim, UpLo::Lo, SourceFrame> > > CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian (const tnsr::I< T, dim, SourceFrame > & source_point) const
Compute the Jacobian of the Maps... at the point(s) source_point
jacobian() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr auto CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian (const tnsr::I< T, dim, SourceFrame > & source_point) const -> Tensor<T, tmpl::integral_list<std::int32_t, 2, 1>, index_list<SpatialIndex<dim, UpLo::Up, TargetFrame>, SpatialIndex<dim, UpLo::Lo, SourceFrame>>>
References gsl::at(), CoordinateMap< SourceFrame, TargetFrame, Maps >::dim, and LIKELY.
operator()() [1/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr tnsr::I<T, dim, TargetFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::operator() (const tnsr::I< T, dim, SourceFrame > & source_point) const
Apply the Maps... to the point(s) source_point
operator()() [2/2]
template<typename SourceFrame, typename TargetFrame, typename... Maps> template<typename T > constexpr tnsr::I<T, CoordinateMap<SourceFrame, TargetFrame, Maps...>::dim, TargetFrame> CoordinateMap< SourceFrame, TargetFrame, Maps >::operator() (const tnsr::I< T, dim, SourceFrame > & source_point) const
References CoordinateMap< SourceFrame, TargetFrame, Maps >::dim, and tuple_fold().
pup()
template<typename SourceFrame, typename TargetFrame, typename... Maps> void CoordinateMap< SourceFrame, TargetFrame, Maps >::pup (PUP::er & p) inline
Friends And Related Function Documentation
operator==
template<typename SourceFrame, typename TargetFrame, typename... Maps> bool operator== (const CoordinateMap< SourceFrame, TargetFrame, Maps > & lhs, const CoordinateMap< SourceFrame, TargetFrame, Maps > & rhs) friend
Member Data Documentation
dim
template<typename SourceFrame, typename TargetFrame, typename... Maps> constexpr size_t CoordinateMap< SourceFrame, TargetFrame, Maps >::dim = CoordinateMaps::map_dim<Maps...> static
Referenced by CoordinateMap< SourceFrame, TargetFrame, Maps >::CoordinateMap(), CoordinateMap< SourceFrame, TargetFrame, Maps >::inv_jacobian(), CoordinateMap< SourceFrame, TargetFrame, Maps >::jacobian(), and CoordinateMap< SourceFrame, TargetFrame, Maps >::operator()().
The documentation for this class was generated from the following file:
src/Domain/CoordinateMaps/CoordinateMap.hpp