SpECTRE: Direction< VolumeDim > Class Template Reference
Direction< VolumeDim > Class Template Reference
Computational Domain
A particular Side along a particular coordinate Axis.
#include <Direction.hpp>
Public Member Functions
Direction (Axis axis, Side side) noexcept
Construct by specifying an Axis and a Side.
Direction (size_t dimension, Side side) noexcept
Construct by specifying a dimension and a Side.
Direction () noexcept
Default constructor for Charm++ serialization.
size_t dimension () const noexcept
The dimension of the Direction.
Axis axis () const noexcept
The Axis of the Direction.
Side side () const noexcept
The side of the Direction.
double sign () const noexcept
The sign for the normal to the Side.
Direction< VolumeDim > opposite () const noexcept
The opposite Direction.
void pup (PUP::er &p)
Serialization for Charm++.
template<>
Direction (const size_t dimension, const Side side) noexcept
template<>
Direction (const size_t dimension, const Side side) noexcept
template<>
Direction (const size_t dimension, const Side side) noexcept
template<>
std::array< Direction< 1 >, 2 > all_directions () noexcept
template<>
std::array< Direction< 2 >, 4 > all_directions () noexcept
template<>
std::array< Direction< 3 >, 6 > all_directions () noexcept
Static Public Member Functions
static std::array< Direction< VolumeDim >, 2 *VolumeDim > all_directions () noexcept
static Direction< VolumeDim > lower_xi () noexcept
Helper functions for creating specific Directions. These are labeled by the logical-coordinate names (Xi,Eta,Zeta).
static Direction< VolumeDim > upper_xi () noexcept
static Direction< VolumeDim > lower_eta () noexcept
static Direction< VolumeDim > upper_eta () noexcept
static Direction< VolumeDim > lower_zeta () noexcept
static Direction< VolumeDim > upper_zeta () noexcept
Detailed Description
template<size_t VolumeDim>
class Direction< VolumeDim >
A particular Side along a particular coordinate Axis.
Constructor & Destructor Documentation
Direction() [1/6]
template<size_t VolumeDim> Direction< VolumeDim >::Direction (Axis axis, Side side) inline noexcept
Construct by specifying an Axis and a Side.
References Direction< VolumeDim >::dimension(), Direction< VolumeDim >::Direction(), and Direction< VolumeDim >::side().
Direction() [2/6]
template<size_t VolumeDim> Direction< VolumeDim >::Direction (size_t dimension, Side side) noexcept
Construct by specifying a dimension and a Side.
Direction() [3/6]
template<size_t VolumeDim> Direction< VolumeDim >::Direction () default noexcept
Default constructor for Charm++ serialization.
Referenced by Direction< VolumeDim >::Direction(), Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::lower_zeta(), Direction< VolumeDim >::sign(), Direction< VolumeDim >::upper_eta(), Direction< VolumeDim >::upper_xi(), and Direction< VolumeDim >::upper_zeta().
Direction() [4/6]
template<> Direction< 1 >::Direction (const size_t dimension, const Side side) noexcept
References ASSERT.
Direction() [5/6]
template<> Direction< 2 >::Direction (const size_t dimension, const Side side) noexcept
References ASSERT.
Direction() [6/6]
template<> Direction< 3 >::Direction (const size_t dimension, const Side side) noexcept
References ASSERT.
Member Function Documentation
all_directions() [1/4]
template<size_t VolumeDim> static std::array<Direction<VolumeDim>, 2 * VolumeDim> Direction< VolumeDim >::all_directions () static noexcept
Referenced by Direction< VolumeDim >::sign().
all_directions() [2/4]
template<> std::array< Direction< 1 >, 2 > Direction< 1 >::all_directions () inline noexcept
References Direction< VolumeDim >::lower_xi(), and Direction< VolumeDim >::upper_xi().
all_directions() [3/4]
template<> std::array< Direction< 2 >, 4 > Direction< 2 >::all_directions () inline noexcept
References Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::upper_eta(), and Direction< VolumeDim >::upper_xi().
all_directions() [4/4]
template<> std::array< Direction< 3 >, 6 > Direction< 3 >::all_directions () inline noexcept
References Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::lower_zeta(), Direction< VolumeDim >::upper_eta(), Direction< VolumeDim >::upper_xi(), and Direction< VolumeDim >::upper_zeta().
axis()
template<size_t VolumeDim> Axis Direction< VolumeDim >::axis () const inline noexcept
The Axis of the Direction.
dimension()
template<size_t VolumeDim> size_t Direction< VolumeDim >::dimension () const inline noexcept
The dimension of the Direction.
Referenced by Direction< VolumeDim >::Direction(), Orientation< VolumeDim >::mapped(), operator!=(), operator<<(), and operator==().
lower_eta()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::lower_eta () inline static noexcept
References Direction< VolumeDim >::Direction(), and Lower.
Referenced by Direction< VolumeDim >::all_directions(), and Direction< VolumeDim >::sign().
lower_xi()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::lower_xi () inline static noexcept
Helper functions for creating specific Directions. These are labeled by the logical-coordinate names (Xi,Eta,Zeta).
References Direction< VolumeDim >::Direction(), and Lower.
Referenced by Direction< VolumeDim >::all_directions(), Direction< VolumeDim >::sign(), and TEST_CASE().
lower_zeta()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::lower_zeta () inline static noexcept
References Direction< VolumeDim >::Direction(), and Lower.
Referenced by Direction< VolumeDim >::all_directions(), and Direction< VolumeDim >::sign().
opposite()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::opposite () const inline noexcept
The opposite Direction.
Referenced by Direction< VolumeDim >::sign().
pup()
template<size_t VolumeDim> void Direction< VolumeDim >::pup (PUP::er & p)
Serialization for Charm++.
Referenced by Direction< VolumeDim >::sign().
side()
template<size_t VolumeDim> Side Direction< VolumeDim >::side () const inline noexcept
The side of the Direction.
Referenced by Direction< VolumeDim >::Direction(), and Orientation< VolumeDim >::mapped().
sign()
template<size_t VolumeDim> double Direction< VolumeDim >::sign () const inline noexcept
The sign for the normal to the Side.
References Direction< VolumeDim >::all_directions(), Direction< VolumeDim >::Direction(), Lower, Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Direction< VolumeDim >::lower_zeta(), operator<<(), Direction< VolumeDim >::opposite(), Direction< VolumeDim >::pup(), Direction< VolumeDim >::upper_eta(), Direction< VolumeDim >::upper_xi(), and Direction< VolumeDim >::upper_zeta().
Referenced by operator!=(), operator<<(), and operator==().
upper_eta()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::upper_eta () inline static noexcept
References Direction< VolumeDim >::Direction(), and Upper.
Referenced by Direction< VolumeDim >::all_directions(), Direction< VolumeDim >::sign(), and TEST_CASE().
upper_xi()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::upper_xi () inline static noexcept
References Direction< VolumeDim >::Direction(), and Upper.
Referenced by Direction< VolumeDim >::all_directions(), Direction< VolumeDim >::sign(), and TEST_CASE().
upper_zeta()
template<size_t VolumeDim> Direction< VolumeDim > Direction< VolumeDim >::upper_zeta () inline static noexcept
References Direction< VolumeDim >::Direction(), and Upper.
Referenced by Direction< VolumeDim >::all_directions(), Direction< VolumeDim >::sign(), and TEST_CASE().
The documentation for this class was generated from the following file:
src/Domain/Direction.hpp