SpECTRE: CoordinateMaps::Identity< Dim > Class Template Reference
CoordinateMaps::Identity< Dim > Class Template Reference
Coordinate Maps
Identity map from \(\xi \rightarrow x\).
#include <Identity.hpp>
Public Member Functions
Identity ()=default
~Identity ()=default
Identity (const Identity &)=default
Identity (Identity &&) noexcept=default
Identity & operator= (const Identity &)=default
Identity & operator= (Identity &&)=default
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, Dim > operator() (const std::array< T, Dim > &xi) const
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, Dim > inverse (const std::array< T, Dim > &x) const
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, Frame::NoFrame >, SpatialIndex< Dim, UpLo::Lo, Frame::NoFrame > > > jacobian (const std::array< T, Dim > &) const
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, Frame::NoFrame >, SpatialIndex< Dim, UpLo::Lo, Frame::NoFrame > > > inv_jacobian (const std::array< T, Dim > &) const
void pup (PUP::er &)
Static Public Attributes
static constexpr size_t dim = Dim
Detailed Description
template<size_t Dim>
class CoordinateMaps::Identity< Dim >
Identity map from \(\xi \rightarrow x\).
Constructor & Destructor Documentation
Identity() [1/3]
template<size_t Dim> CoordinateMaps::Identity< Dim >::Identity () default
~Identity()
template<size_t Dim> CoordinateMaps::Identity< Dim >::~Identity () default
Identity() [2/3]
template<size_t Dim> CoordinateMaps::Identity< Dim >::Identity (const Identity< Dim > &) default
Identity() [3/3]
template<size_t Dim> CoordinateMaps::Identity< Dim >::Identity (Identity< Dim > &&) default noexcept
Member Function Documentation
inv_jacobian()
template<size_t Dim> template<typename T > Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, Frame::NoFrame >, SpatialIndex< Dim, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::Identity< Dim >::inv_jacobian (const std::array< T, Dim > &) const
References CoordinateMaps::Identity< Dim >::inverse(), CoordinateMaps::Identity< Dim >::jacobian(), and CoordinateMaps::Identity< Dim >::operator()().
Referenced by test_identity().
inverse()
template<size_t Dim> template<typename T > std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, Dim > CoordinateMaps::Identity< Dim >::inverse (const std::array< T, Dim > & x) const
Referenced by CoordinateMaps::Identity< Dim >::inv_jacobian(), and test_identity().
jacobian()
template<size_t Dim> template<typename T > Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< Dim, UpLo::Up, Frame::NoFrame >, SpatialIndex< Dim, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::Identity< Dim >::jacobian (const std::array< T, Dim > &) const
Referenced by CoordinateMaps::Identity< Dim >::inv_jacobian(), and test_identity().
operator()()
template<size_t Dim> template<typename T > std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, Dim > CoordinateMaps::Identity< Dim >::operator() (const std::array< T, Dim > & xi) const
Referenced by CoordinateMaps::Identity< Dim >::inv_jacobian().
operator=() [1/2]
template<size_t Dim> Identity& CoordinateMaps::Identity< Dim >::operator= (const Identity< Dim > &) default
operator=() [2/2]
template<size_t Dim> Identity& CoordinateMaps::Identity< Dim >::operator= (Identity< Dim > &&) default
pup()
template<size_t Dim> void CoordinateMaps::Identity< Dim >::pup (PUP::er &) inline
Member Data Documentation
dim
template<size_t Dim> constexpr size_t CoordinateMaps::Identity< Dim >::dim = Dim static
The documentation for this class was generated from the following files:
src/Domain/CoordinateMaps/Identity.hpp
src/Domain/CoordinateMaps/Identity.cpp