SpECTRE: CoordinateMaps::Rotation< 3 > Class Template Reference
CoordinateMaps::Rotation< 3 > Class Template Reference
Coordinate Maps
Spatial rotation in three dimensions using Euler angles.
#include <Rotation.hpp>
Public Member Functions
Rotation (double rotation_about_z, double rotation_about_rotated_y, double rotation_about_rotated_z)
Constructor.
Rotation ()=default
~Rotation ()=default
Rotation (const Rotation &)=default
Rotation & operator= (const Rotation &)=default
Rotation (Rotation &&) noexcept=default
Rotation & operator= (Rotation &&)=default
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, 3 > operator() (const std::array< T, 3 > &xi) const
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, 3 > inverse (const std::array< T, 3 > &x) const
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 3, UpLo::Up, Frame::NoFrame >, SpatialIndex< 3, UpLo::Lo, Frame::NoFrame > > > jacobian (const std::array< T, 3 > &) const
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 3, UpLo::Up, Frame::NoFrame >, SpatialIndex< 3, UpLo::Lo, Frame::NoFrame > > > inv_jacobian (const std::array< T, 3 > &) const
void pup (PUP::er &p)
Static Public Attributes
static constexpr size_t dim = 3
Friends
bool operator== (const Rotation< 3 > &lhs, const Rotation< 3 > &rhs) noexcept
Detailed Description
template<>
class CoordinateMaps::Rotation< 3 >
Spatial rotation in three dimensions using Euler angles.
Rotation angles should be specified in degrees. First rotation \(\alpha\) is about z axis. Second rotation \(\beta\) is about rotated y axis. Third rotation \(\gamma\) is about rotated z axis. These rotations are of the \((\xi,\eta,\zeta)\) coordinate system with respect to the grid coordinates \((x,y,z)\).
The formula for the mapping is:
\begin{eqnarray*} x &=& \xi (\cos\gamma \cos\beta \cos\alpha - \sin\gamma \sin\alpha) + \eta (-\sin\gamma \cos\beta \cos\alpha - \cos\gamma \sin\alpha) + \zeta \sin\beta \cos\alpha \\ y &=& \xi (\cos\gamma \cos\beta \sin\alpha + \sin\gamma \cos\alpha) + \eta (-\sin\gamma \cos\beta \sin\alpha + \cos\gamma \cos\alpha) + \zeta \sin\beta \sin\alpha \\ z &=& -\xi \cos\gamma \sin\beta + \eta \sin\gamma \sin\beta + \zeta \cos\beta \end{eqnarray*}
Constructor & Destructor Documentation
Rotation() [1/4]
CoordinateMaps::Rotation< 3 >::Rotation (double rotation_about_z, double rotation_about_rotated_y, double rotation_about_rotated_z)
Constructor.
Parameters
rotation_about_z the angle \(\alpha\) (in radians).
rotation_about_rotated_y the angle \(\beta\) (in radians).
rotation_about_rotated_z the angle \(\gamma\) (in radians).
References operator()().
Rotation() [2/4]
CoordinateMaps::Rotation< 3 >::Rotation () default
~Rotation()
CoordinateMaps::Rotation< 3 >::~Rotation () default
Rotation() [3/4]
CoordinateMaps::Rotation< 3 >::Rotation (const Rotation< 3 > &) default
Rotation() [4/4]
CoordinateMaps::Rotation< 3 >::Rotation (Rotation< 3 > &&) default noexcept
Member Function Documentation
inv_jacobian()
template<typename T > template Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 3, UpLo::Up, Frame::NoFrame >, SpatialIndex< 3, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::Rotation< 3 >::inv_jacobian (const std::array< T, 3 > &) const
Referenced by CoordinateMaps::operator!=(), and test_rotation_3().
inverse()
template<typename T > template std::array< DataVector, 3 > CoordinateMaps::Rotation< 3 >::inverse (const std::array< T, 3 > & x) const
Referenced by CoordinateMaps::operator!=(), and test_rotation_3().
jacobian()
template<typename T > template Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 3, UpLo::Up, Frame::NoFrame >, SpatialIndex< 3, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::Rotation< 3 >::jacobian (const std::array< T, 3 > &) const
Referenced by CoordinateMaps::operator!=(), and test_rotation_3().
operator()()
template<typename T > template std::array< DataVector, 3 > CoordinateMaps::Rotation< 3 >::operator() (const std::array< T, 3 > & xi) const
Referenced by CoordinateMaps::operator!=(), and Rotation().
operator=() [1/2]
Rotation& CoordinateMaps::Rotation< 3 >::operator= (const Rotation< 3 > &) default
operator=() [2/2]
Rotation& CoordinateMaps::Rotation< 3 >::operator= (Rotation< 3 > &&) default
pup()
void CoordinateMaps::Rotation< 3 >::pup (PUP::er & p)
Friends And Related Function Documentation
operator==
bool operator== (const Rotation< 3 > & lhs, const Rotation< 3 > & rhs) friend
Member Data Documentation
dim
constexpr size_t CoordinateMaps::Rotation< 3 >::dim = 3 static
The documentation for this class was generated from the following files:
src/Domain/CoordinateMaps/Rotation.hpp
src/Domain/CoordinateMaps/Rotation.cpp