SpECTRE: Orientation< VolumeDim > Class Template Reference
Orientation< VolumeDim > Class Template Reference
Domain Creators
Allows one to construct a custom Orientation between two Blocks.
#include <Orientation.hpp>
Public Member Functions
Orientation ()=default
Orientation (std::array< Direction< VolumeDim >, VolumeDim > mapped_directions)
Orientation (const std::array< Direction< VolumeDim >, VolumeDim > &directions_in_host, const std::array< Direction< VolumeDim >, VolumeDim > &directions_in_neighbor)
~Orientation ()=default
Orientation (const Orientation &)=default
Orientation & operator= (const Orientation &)=default
Orientation (Orientation &&) noexcept=default
Orientation & operator= (Orientation &&) noexcept=default
bool is_aligned () const noexcept
True when mapped(Direction) == Direction.
size_t mapped (const size_t dim) const noexcept
The corresponding dimension in the neighbor.
Direction< VolumeDim > mapped (const Direction< VolumeDim > &direction) const
The corresponding direction in the neighbor.
std::array< SegmentId, VolumeDim > mapped (const std::array< SegmentId, VolumeDim > &segmentIds) const
The corresponding SegmentIds in the neighbor.
void pup (PUP::er &p)
Serialization for Charm++.
Friends
template<size_t VolumeDimLocal>
bool operator== (const Orientation< VolumeDimLocal > &lhs, const Orientation< VolumeDimLocal > &rhs) noexcept
Detailed Description
template<size_t VolumeDim>
class Orientation< VolumeDim >
Allows one to construct a custom Orientation between two Blocks.
Usage
The user provides 2*VolumeDim Directions, encoding the correspondence between the directions in each block.
Template Parameters
VolumeDim the dimension of the blocks.
Constructor & Destructor Documentation
Orientation() [1/5]
template<size_t VolumeDim> Orientation< VolumeDim >::Orientation () default
Orientation() [2/5]
template<size_t VolumeDim> Orientation< VolumeDim >::Orientation (std::array< Direction< VolumeDim >, VolumeDim > mapped_directions)
References Upper.
Orientation() [3/5]
template<size_t VolumeDim> Orientation< VolumeDim >::Orientation (const std::array< Direction< VolumeDim >, VolumeDim > & directions_in_host, const std::array< Direction< VolumeDim >, VolumeDim > & directions_in_neighbor)
References Upper.
~Orientation()
template<size_t VolumeDim> Orientation< VolumeDim >::~Orientation () default
Orientation() [4/5]
template<size_t VolumeDim> Orientation< VolumeDim >::Orientation (const Orientation< VolumeDim > &) default
Orientation() [5/5]
template<size_t VolumeDim> Orientation< VolumeDim >::Orientation (Orientation< VolumeDim > &&) default noexcept
Member Function Documentation
is_aligned()
template<size_t VolumeDim> bool Orientation< VolumeDim >::is_aligned () const inline noexcept
True when mapped(Direction) == Direction.
mapped() [1/3]
template<size_t VolumeDim> size_t Orientation< VolumeDim >::mapped (const size_t dim) const inline noexcept
The corresponding dimension in the neighbor.
Referenced by Orientation< VolumeDim >::mapped().
mapped() [2/3]
template<size_t VolumeDim> Direction<VolumeDim> Orientation< VolumeDim >::mapped (const Direction< VolumeDim > & direction) const inline
The corresponding direction in the neighbor.
References Direction< VolumeDim >::dimension(), Orientation< VolumeDim >::mapped(), operator<<(), Orientation< VolumeDim >::operator==, Orientation< VolumeDim >::pup(), Direction< VolumeDim >::side(), and Upper.
mapped() [3/3]
template<size_t VolumeDim> std::array< SegmentId, VolumeDim > Orientation< VolumeDim >::mapped (const std::array< SegmentId, VolumeDim > & segmentIds) const
The corresponding SegmentIds in the neighbor.
References Upper.
operator=() [1/2]
template<size_t VolumeDim> Orientation& Orientation< VolumeDim >::operator= (const Orientation< VolumeDim > &) default
operator=() [2/2]
template<size_t VolumeDim> Orientation& Orientation< VolumeDim >::operator= (Orientation< VolumeDim > &&) default noexcept
pup()
template<size_t VolumeDim> void Orientation< VolumeDim >::pup (PUP::er & p)
Serialization for Charm++.
Referenced by Orientation< VolumeDim >::mapped().
Friends And Related Function Documentation
operator==
template<size_t VolumeDim> template<size_t VolumeDimLocal> bool operator== (const Orientation< VolumeDimLocal > & lhs, const Orientation< VolumeDimLocal > & rhs) friend
Referenced by Orientation< VolumeDim >::mapped().
The documentation for this class was generated from the following files:
src/Domain/Orientation.hpp
src/Domain/Orientation.cpp