SpECTRE: Block< VolumeDim > Class Template Reference
Block< VolumeDim > Class Template Reference
Computational Domain
A Block<VolumeDim> is a region of a VolumeDim-dimensional computational domain that defines the root node of a tree which is used to construct the Elements that cover a region of the computational domain.
#include <Block.hpp>
Public Member Functions
Block (const EmbeddingMap< VolumeDim, VolumeDim > &embedding_map, size_t id, std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim >> &&neighbors)
Block ()=default
~Block ()=default
Block (const Block< VolumeDim > &)=delete
Block (Block< VolumeDim > &&)=default
Block< VolumeDim > & operator= (const Block< VolumeDim > &)=delete
Block< VolumeDim > & operator= (Block< VolumeDim > &&)=default
const EmbeddingMap< VolumeDim, VolumeDim > & embedding_map () const noexcept
size_t id () const noexcept
A unique identifier for the Block that is in the range [0, number_of_blocks -1] where number_of_blocks is the number of Blocks that cover the computational domain.
const std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim > > & neighbors () const noexcept
Information about the neighboring Blocks.
const std::unordered_set< Direction< VolumeDim > > & external_boundaries () const noexcept
The directions of the faces of the Block that are external boundaries.
void pup (PUP::er &p)
Serialization for Charm++.
Detailed Description
template<size_t VolumeDim>
class Block< VolumeDim >
A Block<VolumeDim> is a region of a VolumeDim-dimensional computational domain that defines the root node of a tree which is used to construct the Elements that cover a region of the computational domain.
Each codimension 1 boundary of a Block<VolumeDim> is either an external boundary or identical to a boundary of one other Block.
A Block has logical coordinates that go from -1 to +1 in each dimension. The global coordinates are obtained from the logical coordinates from the EmbeddingMap: EmbeddingMap::operator() takes Points in the Logical Frame (i.e., logical coordinates) and returns Points in the Grid Frame (i.e., global coordinates).
Template Parameters
VolumeDim the dimension of the Block (i.e. the volume dimension).
Constructor & Destructor Documentation
Block() [1/4]
template<size_t VolumeDim> Block< VolumeDim >::Block (const EmbeddingMap< VolumeDim, VolumeDim > & embedding_map, size_t id, std::unordered_map< Direction< VolumeDim >, BlockNeighbor< VolumeDim >> && neighbors)
Parameters
embedding_map the EmbeddingMap.
id a unique ID.
neighbors info about the Blocks that share a codimension 1 boundary with this Block.
Block() [2/4]
template<size_t VolumeDim> Block< VolumeDim >::Block () default
~Block()
template<size_t VolumeDim> Block< VolumeDim >::~Block () default
Block() [3/4]
template<size_t VolumeDim> Block< VolumeDim >::Block (const Block< VolumeDim > &) delete
Block() [4/4]
template<size_t VolumeDim> Block< VolumeDim >::Block (Block< VolumeDim > &&) default
Member Function Documentation
embedding_map()
template<size_t VolumeDim> const EmbeddingMap<VolumeDim, VolumeDim>& Block< VolumeDim >::embedding_map () const inline noexcept
external_boundaries()
template<size_t VolumeDim> const std::unordered_set<Direction<VolumeDim> >& Block< VolumeDim >::external_boundaries () const inline noexcept
The directions of the faces of the Block that are external boundaries.
References operator!=(), operator==(), and Block< VolumeDim >::pup().
Referenced by TEST_CASE().
id()
template<size_t VolumeDim> size_t Block< VolumeDim >::id () const inline noexcept
A unique identifier for the Block that is in the range [0, number_of_blocks -1] where number_of_blocks is the number of Blocks that cover the computational domain.
Referenced by TEST_CASE().
neighbors()
template<size_t VolumeDim> const std::unordered_map<Direction<VolumeDim>, BlockNeighbor<VolumeDim> >& Block< VolumeDim >::neighbors () const inline noexcept
Information about the neighboring Blocks.
Referenced by TEST_CASE().
operator=() [1/2]
template<size_t VolumeDim> Block<VolumeDim>& Block< VolumeDim >::operator= (const Block< VolumeDim > &) delete
operator=() [2/2]
template<size_t VolumeDim> Block<VolumeDim>& Block< VolumeDim >::operator= (Block< VolumeDim > &&) default
pup()
template<size_t VolumeDim> void Block< VolumeDim >::pup (PUP::er & p)
Serialization for Charm++.
Referenced by Block< VolumeDim >::external_boundaries().
The documentation for this class was generated from the following files:
src/Domain/Block.hpp
src/Domain/Block.cpp