SpECTRE: EmbeddingMaps::Rotation< 3 > Class Template Reference
EmbeddingMaps::Rotation< 3 > Class Template Reference
#include <Rotation.hpp>
Public Member Functions
Rotation (double rotation_about_z, double rotation_about_rotated_y, double rotation_about_rotated_z)
Constructor.
Rotation ()=default
~Rotation () override=default
Rotation (const Rotation &)=delete
Rotation & operator= (const Rotation &)=delete
Rotation (Rotation &&) noexcept=default
Rotation & operator= (Rotation &&)=delete
std::unique_ptr< EmbeddingMap< 3, 3 > > get_clone () const override
Return a copy of the concrete EmbeddingMap.
Point< 3, Frame::Grid > operator() (const Point< 3, Frame::Logical > &xi) const override
Point< 3, Frame::Logical > inverse (const Point< 3, Frame::Grid > &x) const override
double jacobian (const Point< 3, Frame::Logical > &xi, size_t ud, size_t ld) const override
double inv_jacobian (const Point< 3, Frame::Logical > &xi, size_t ud, size_t ld) const override
WRAPPED_PUPable_decl_base_template (SINGLE_ARG(EmbeddingMap< 3, 3 >), Rotation)
Rotation (CkMigrateMessage *m)
void pup (PUP::er &p) override
Public Member Functions inherited from EmbeddingMap< 3, 3 >
WRAPPED_PUPable_abstract (EmbeddingMap)
EmbeddingMap ()=default
EmbeddingMap (const EmbeddingMap< DimOfDomain, DimOfRange > &)=delete
EmbeddingMap (EmbeddingMap< DimOfDomain, DimOfRange > &&) noexcept=default
~EmbeddingMap () override=default
EmbeddingMap< DimOfDomain, DimOfRange > & operator= (const EmbeddingMap< DimOfDomain, DimOfRange > &)=delete
EmbeddingMap< DimOfDomain, DimOfRange > & operator= (EmbeddingMap< DimOfDomain, DimOfRange > &&) noexcept=default
virtual Point< DimOfRange, Frame::Grid > operator() (const Point< DimOfDomain, Frame::Logical > &xi) const=0
Apply the mapping (i.e. compute \(x^i(\xi^I)\)).
virtual Point< DimOfDomain, Frame::Logical > inverse (const Point< DimOfRange, Frame::Grid > &x) const=0
Apply the inverse mapping (i.e. compute \(\xi^I(x^i)\)).
virtual double jacobian (const Point< DimOfDomain, Frame::Logical > &xi, size_t ud, size_t ld) const=0
virtual double inv_jacobian (const Point< DimOfDomain, Frame::Logical > &xi, size_t ud, size_t ld) const=0
(i.e. compute \(\frac{\partial \xi^{ud}}{\partial x^{ld}}\)).
Detailed Description
template<>
class EmbeddingMaps::Rotation< 3 >
Spatial rotation in three dimensions using Euler angles
Rotation angles should be specified in degrees. First rotation \(\alpha\) is about z axis. Second rotation \(\beta\) is about rotated y axis. Third rotation \(\gamma\) is about rotated z axis. These rotations are of the \((\xi,\eta,\zeta)\) coordinate system with respect to the grid coordinates \((x,y,z)\).
The formula for the mapping is:
\begin{eqnarray*} x &=& \xi (\cos\gamma \cos\beta \cos\alpha - \sin\gamma \sin\alpha) + \eta (-\sin\gamma \cos\beta \cos\alpha - \cos\gamma \sin\alpha) + \zeta \sin\beta \cos\alpha \\ y &=& \xi (\cos\gamma \cos\beta \sin\alpha + \sin\gamma \cos\alpha) + \eta (-\sin\gamma \cos\beta \sin\alpha + \cos\gamma \cos\alpha) + \zeta \sin\beta \sin\alpha \\ z &=& -\xi \cos\gamma \sin\beta + \eta \sin\gamma \sin\beta + \zeta \cos\beta \end{eqnarray*}
Constructor & Destructor Documentation
Rotation() [1/5]
EmbeddingMaps::Rotation< 3 >::Rotation (double rotation_about_z, double rotation_about_rotated_y, double rotation_about_rotated_z)
Constructor.
Parameters
rotation_about_z the angle \(\alpha\) (in radians).
rotation_about_rotated_y the angle \(\beta\) (in radians).
rotation_about_rotated_z the angle \(\gamma\) (in radians).
Rotation() [2/5]
EmbeddingMaps::Rotation< 3 >::Rotation () default
~Rotation()
EmbeddingMaps::Rotation< 3 >::~Rotation () override default
Rotation() [3/5]
EmbeddingMaps::Rotation< 3 >::Rotation (const Rotation< 3 > &) delete
Rotation() [4/5]
EmbeddingMaps::Rotation< 3 >::Rotation (Rotation< 3 > &&) default noexcept
Rotation() [5/5]
EmbeddingMaps::Rotation< 3 >::Rotation (CkMigrateMessage * m) explicit
Member Function Documentation
get_clone()
std::unique_ptr< EmbeddingMap< 3, 3 > > EmbeddingMaps::Rotation< 3 >::get_clone () const override virtual
Return a copy of the concrete EmbeddingMap.
Implements EmbeddingMap< 3, 3 >.
Referenced by test_rotation_3().
inv_jacobian()
double EmbeddingMaps::Rotation< 3 >::inv_jacobian (const Point< 3, Frame::Logical > & xi, size_t ud, size_t ld) const override
References ASSERT.
Referenced by test_rotation_3().
inverse()
Point< 3, Frame::Logical > EmbeddingMaps::Rotation< 3 >::inverse (const Point< 3, Frame::Grid > & x) const override
Referenced by test_rotation_3().
jacobian()
double EmbeddingMaps::Rotation< 3 >::jacobian (const Point< 3, Frame::Logical > & xi, size_t ud, size_t ld) const override
References ASSERT.
Referenced by test_rotation_3().
operator()()
Point< 3, Frame::Grid > EmbeddingMaps::Rotation< 3 >::operator() (const Point< 3, Frame::Logical > & xi) const override
operator=() [1/2]
Rotation& EmbeddingMaps::Rotation< 3 >::operator= (const Rotation< 3 > &) delete
operator=() [2/2]
Rotation& EmbeddingMaps::Rotation< 3 >::operator= (Rotation< 3 > &&) delete
pup()
void EmbeddingMaps::Rotation< 3 >::pup (PUP::er & p) override
WRAPPED_PUPable_decl_base_template()
EmbeddingMaps::Rotation< 3 >::WRAPPED_PUPable_decl_base_template (SINGLE_ARG(EmbeddingMap< 3, 3 >) , Rotation< 3 >)
The documentation for this class was generated from the following files:
src/Domain/EmbeddingMaps/Rotation.hpp
src/Domain/EmbeddingMaps/Rotation.cpp