SpECTRE: EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 > Class Template Reference
EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 > Class Template Reference final
Embedding Maps
Product of two codimension=0 EmbeddingMaps.
#include <ProductMaps.hpp>
Public Member Functions
ProductOf2Maps (const EmbeddingMap< Dim1, Dim1 > &map_1, const EmbeddingMap< Dim2, Dim2 > &map_2)
ProductOf2Maps ()=default
~ProductOf2Maps () override=default
ProductOf2Maps (const ProductOf2Maps< Dim1, Dim2 > &other)
ProductOf2Maps< Dim1, Dim2 > & operator= (const ProductOf2Maps< Dim1, Dim2 > &)=delete
ProductOf2Maps (ProductOf2Maps< Dim1, Dim2 > &&) noexcept=default
ProductOf2Maps< Dim1, Dim2 > & operator= (ProductOf2Maps< Dim1, Dim2 > &&)=delete
std::unique_ptr< EmbeddingMap< Dim1+Dim2, Dim1+Dim2 > > get_clone () const override
Return a copy of the concrete EmbeddingMap.
Point< Dim1+Dim2, Frame::Grid > operator() (const Point< Dim1+Dim2, Frame::Logical > &xi) const override
Point< Dim1+Dim2, Frame::Logical > inverse (const Point< Dim1+Dim2, Frame::Grid > &x) const override
double jacobian (const Point< Dim1+Dim2, Frame::Logical > &xi, size_t ud, size_t ld) const override
double inv_jacobian (const Point< Dim1+Dim2, Frame::Logical > &xi, size_t ud, size_t ld) const override
WRAPPED_PUPable_decl_base_template (SINGLE_ARG(EmbeddingMap< Dim1+Dim2, Dim1+Dim2 >), ProductOf2Maps)
ProductOf2Maps (CkMigrateMessage *)
void pup (PUP::er &p) override
template<>
Point< 2, Frame::Grid > operator() (const Point< 2, Frame::Logical > &xi) const
template<>
Point< 2, Frame::Logical > inverse (const Point< 2, Frame::Grid > &x) const
template<>
double jacobian (const Point< 2, Frame::Logical > &xi, const size_t ud, const size_t ld) const
template<>
double inv_jacobian (const Point< 2, Frame::Logical > &xi, const size_t ud, const size_t ld) const
template<>
ProductOf2Maps (CkMigrateMessage *)
template<>
void pup (PUP::er &p)
Public Member Functions inherited from EmbeddingMap< Dim1+Dim2, Dim1+Dim2 >
WRAPPED_PUPable_abstract (EmbeddingMap)
EmbeddingMap ()=default
EmbeddingMap (const EmbeddingMap< DimOfDomain, DimOfRange > &)=delete
EmbeddingMap (EmbeddingMap< DimOfDomain, DimOfRange > &&) noexcept=default
~EmbeddingMap () override=default
EmbeddingMap< DimOfDomain, DimOfRange > & operator= (const EmbeddingMap< DimOfDomain, DimOfRange > &)=delete
EmbeddingMap< DimOfDomain, DimOfRange > & operator= (EmbeddingMap< DimOfDomain, DimOfRange > &&) noexcept=default
virtual Point< DimOfRange, Frame::Grid > operator() (const Point< DimOfDomain, Frame::Logical > &xi) const=0
Apply the mapping (i.e. compute \(x^i(\xi^I)\)).
virtual Point< DimOfDomain, Frame::Logical > inverse (const Point< DimOfRange, Frame::Grid > &x) const=0
Apply the inverse mapping (i.e. compute \(\xi^I(x^i)\)).
virtual double jacobian (const Point< DimOfDomain, Frame::Logical > &xi, size_t ud, size_t ld) const=0
virtual double inv_jacobian (const Point< DimOfDomain, Frame::Logical > &xi, size_t ud, size_t ld) const=0
(i.e. compute \(\frac{\partial \xi^{ud}}{\partial x^{ld}}\)).
Detailed Description
template<size_t Dim1, size_t Dim2>
class EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >
Product of two codimension=0 EmbeddingMaps.
Template Parameters
Dim1 dimension of the domain and range of the first mapping.
Dim2 dimension of the domain and range of the second mapping.
Constructor & Destructor Documentation
ProductOf2Maps() [1/6]
template<size_t Dim1, size_t Dim2> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::ProductOf2Maps (const EmbeddingMap< Dim1, Dim1 > & map_1, const EmbeddingMap< Dim2, Dim2 > & map_2)
ProductOf2Maps() [2/6]
template<size_t Dim1, size_t Dim2> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::ProductOf2Maps () default
Referenced by EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::get_clone().
~ProductOf2Maps()
template<size_t Dim1, size_t Dim2> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::~ProductOf2Maps () override default
ProductOf2Maps() [3/6]
template<size_t Dim1, size_t Dim2> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::ProductOf2Maps (const ProductOf2Maps< Dim1, Dim2 > & other)
ProductOf2Maps() [4/6]
template<size_t Dim1, size_t Dim2> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::ProductOf2Maps (ProductOf2Maps< Dim1, Dim2 > &&) default noexcept
ProductOf2Maps() [5/6]
template<size_t Dim1, size_t Dim2> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::ProductOf2Maps (CkMigrateMessage *) explicit
ProductOf2Maps() [6/6]
template<> EmbeddingMaps::ProductOf2Maps< 1, 1 >::ProductOf2Maps (CkMigrateMessage *)
Member Function Documentation
get_clone()
template<size_t Dim1, size_t Dim2> std::unique_ptr<EmbeddingMap<Dim1 + Dim2, Dim1 + Dim2> > EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::get_clone () const inline override virtual
Return a copy of the concrete EmbeddingMap.
Implements EmbeddingMap< Dim1+Dim2, Dim1+Dim2 >.
References EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::inv_jacobian(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::inverse(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::jacobian(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::operator()(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::ProductOf2Maps(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::pup(), and EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::WRAPPED_PUPable_decl_base_template().
inv_jacobian() [1/2]
template<size_t Dim1, size_t Dim2> double EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::inv_jacobian (const Point< Dim1+Dim2, Frame::Logical > & xi, size_t ud, size_t ld) const override
Referenced by EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::get_clone(), and EmbeddingMaps::ProductOf3Maps::get_clone().
inv_jacobian() [2/2]
template<> double EmbeddingMaps::ProductOf2Maps< 1, 1 >::inv_jacobian (const Point< 2, Frame::Logical > & xi, const size_t ud, const size_t ld) const
References ASSERT.
inverse() [1/2]
template<> Point< 2, Frame::Logical > EmbeddingMaps::ProductOf2Maps< 1, 1 >::inverse (const Point< 2, Frame::Grid > & x) const
inverse() [2/2]
template<size_t Dim1, size_t Dim2> Point<Dim1 + Dim2, Frame::Logical> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::inverse (const Point< Dim1+Dim2, Frame::Grid > & x) const override
Referenced by EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::get_clone(), and EmbeddingMaps::ProductOf3Maps::get_clone().
jacobian() [1/2]
template<> double EmbeddingMaps::ProductOf2Maps< 1, 1 >::jacobian (const Point< 2, Frame::Logical > & xi, const size_t ud, const size_t ld) const
References ASSERT.
jacobian() [2/2]
template<size_t Dim1, size_t Dim2> double EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::jacobian (const Point< Dim1+Dim2, Frame::Logical > & xi, size_t ud, size_t ld) const override
Referenced by EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::get_clone(), and EmbeddingMaps::ProductOf3Maps::get_clone().
operator()() [1/2]
template<> Point< 2, Frame::Grid > EmbeddingMaps::ProductOf2Maps< 1, 1 >::operator() (const Point< 2, Frame::Logical > & xi) const
operator()() [2/2]
template<size_t Dim1, size_t Dim2> Point<Dim1 + Dim2, Frame::Grid> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::operator() (const Point< Dim1+Dim2, Frame::Logical > & xi) const override
Referenced by EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::get_clone(), and EmbeddingMaps::ProductOf3Maps::get_clone().
operator=() [1/2]
template<size_t Dim1, size_t Dim2> ProductOf2Maps<Dim1, Dim2>& EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::operator= (const ProductOf2Maps< Dim1, Dim2 > &) delete
operator=() [2/2]
template<size_t Dim1, size_t Dim2> ProductOf2Maps<Dim1, Dim2>& EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::operator= (ProductOf2Maps< Dim1, Dim2 > &&) delete
pup() [1/2]
template<size_t Dim1, size_t Dim2> void EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::pup (PUP::er & p) override
Referenced by EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::get_clone(), and EmbeddingMaps::ProductOf3Maps::get_clone().
pup() [2/2]
template<> void EmbeddingMaps::ProductOf2Maps< 1, 1 >::pup (PUP::er & p)
WRAPPED_PUPable_decl_base_template()
template<size_t Dim1, size_t Dim2> EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::WRAPPED_PUPable_decl_base_template (SINGLE_ARG(EmbeddingMap< Dim1+Dim2, Dim1+Dim2 >) , ProductOf2Maps< Dim1, Dim2 >)
Referenced by EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::get_clone(), and EmbeddingMaps::ProductOf3Maps::get_clone().
The documentation for this class was generated from the following files:
src/Domain/EmbeddingMaps/ProductMaps.hpp
src/Domain/EmbeddingMaps/ProductMaps.cpp