SpECTRE: Time Class Reference
Time Class Reference
Time
The time in a simulation. Times can be safely compared for exact equality as long as they do not belong to overlapping unequal slabs.
#include <Time.hpp>
Public Types
using rational_t = boost::rational< ssize_t >
Public Member Functions
Time () noexcept
Default constructor gives an invalid Time.
Time (Slab slab, rational_t fraction) noexcept
A time a given fraction of the way through the given slab.
Time with_slab (const Slab &new_slab) const noexcept
Move the time to a different slab. The time must be at an end of the current slab and the new slab must share that endpoint.
double value () const noexcept
Approximate numerical value of the Time.
const Slab & slab () const noexcept
const rational_t & fraction () const noexcept
Time & operator+= (const TimeDelta &delta) noexcept
Time & operator-= (const TimeDelta &delta) noexcept
bool is_at_slab_start () const noexcept
bool is_at_slab_end () const noexcept
bool is_at_slab_boundary () const noexcept
void pup (PUP::er &p) noexcept
Friends
class TimeDelta
Detailed Description
The time in a simulation. Times can be safely compared for exact equality as long as they do not belong to overlapping unequal slabs.
Member Typedef Documentation
rational_t
using Time::rational_t = boost::rational<ssize_t>
Constructor & Destructor Documentation
Time() [1/2]
Time::Time () inline noexcept
Default constructor gives an invalid Time.
Time() [2/2]
Time::Time (Slab slab, rational_t fraction) inline noexcept
A time a given fraction of the way through the given slab.
Member Function Documentation
fraction()
const rational_t& Time::fraction () const inline noexcept
References blaze::operator+=(), and blaze::operator-=().
is_at_slab_boundary()
bool Time::is_at_slab_boundary () const inline noexcept
is_at_slab_end()
bool Time::is_at_slab_end () const inline noexcept
Referenced by value().
is_at_slab_start()
bool Time::is_at_slab_start () const inline noexcept
operator+=()
Time & Time::operator+= (const TimeDelta & delta) inline noexcept
References with_slab().
operator-=()
Time & Time::operator-= (const TimeDelta & delta) inline noexcept
References with_slab().
pup()
void Time::pup (PUP::er & p) noexcept
slab()
const Slab& Time::slab () const inline noexcept
value()
double Time::value () const noexcept
Approximate numerical value of the Time.
References Slab::duration(), and is_at_slab_end().
Referenced by integrate_test(), and integrate_variable_test().
with_slab()
Time Time::with_slab (const Slab & new_slab) const noexcept
Move the time to a different slab. The time must be at an end of the current slab and the new slab must share that endpoint.
References ASSERT.
Referenced by operator+=(), and operator-=().
Friends And Related Function Documentation
TimeDelta
friend class TimeDelta friend
Referenced by TimeDelta::operator-(), and operator-().
The documentation for this class was generated from the following files:
src/Time/Time.hpp
src/Time/Time.cpp