SpECTRE: EmbeddingMaps::ProductOf3Maps Class Reference
EmbeddingMaps::ProductOf3Maps Class Reference final
Embedding Maps
Product of three one-dimensional EmbeddingMaps.
#include <ProductMaps.hpp>
Public Member Functions
ProductOf3Maps (const EmbeddingMap< 1, 1 > &map_1, const EmbeddingMap< 1, 1 > &map_2, const EmbeddingMap< 1, 1 > &map_3)
ProductOf3Maps ()=default
~ProductOf3Maps () override=default
ProductOf3Maps (const ProductOf3Maps &other)
ProductOf3Maps & operator= (const ProductOf3Maps &)=delete
ProductOf3Maps (ProductOf3Maps &&) noexcept
ProductOf3Maps & operator= (ProductOf3Maps &&)=default
std::unique_ptr< EmbeddingMap< 3, 3 > > get_clone () const override
Return a copy of the concrete EmbeddingMap.
Point< 3, Frame::Grid > operator() (const Point< 3, Frame::Logical > &xi) const override
Point< 3, Frame::Logical > inverse (const Point< 3, Frame::Grid > &x) const override
double jacobian (const Point< 3, Frame::Logical > &xi, size_t ud, size_t ld) const override
double inv_jacobian (const Point< 3, Frame::Logical > &xi, size_t ud, size_t ld) const override
WRAPPED_PUPable_decl_base_template (SINGLE_ARG(EmbeddingMap< 3, 3 >), ProductOf3Maps)
ProductOf3Maps (CkMigrateMessage *)
void pup (PUP::er &p) override
Public Member Functions inherited from EmbeddingMap< 3, 3 >
WRAPPED_PUPable_abstract (EmbeddingMap)
EmbeddingMap ()=default
EmbeddingMap (const EmbeddingMap< DimOfDomain, DimOfRange > &)=delete
EmbeddingMap (EmbeddingMap< DimOfDomain, DimOfRange > &&) noexcept=default
~EmbeddingMap () override=default
EmbeddingMap< DimOfDomain, DimOfRange > & operator= (const EmbeddingMap< DimOfDomain, DimOfRange > &)=delete
EmbeddingMap< DimOfDomain, DimOfRange > & operator= (EmbeddingMap< DimOfDomain, DimOfRange > &&) noexcept=default
virtual Point< DimOfRange, Frame::Grid > operator() (const Point< DimOfDomain, Frame::Logical > &xi) const=0
Apply the mapping (i.e. compute \(x^i(\xi^I)\)).
virtual Point< DimOfDomain, Frame::Logical > inverse (const Point< DimOfRange, Frame::Grid > &x) const=0
Apply the inverse mapping (i.e. compute \(\xi^I(x^i)\)).
virtual double jacobian (const Point< DimOfDomain, Frame::Logical > &xi, size_t ud, size_t ld) const=0
virtual double inv_jacobian (const Point< DimOfDomain, Frame::Logical > &xi, size_t ud, size_t ld) const=0
(i.e. compute \(\frac{\partial \xi^{ud}}{\partial x^{ld}}\)).
Detailed Description
Product of three one-dimensional EmbeddingMaps.
Constructor & Destructor Documentation
ProductOf3Maps() [1/5]
EmbeddingMaps::ProductOf3Maps::ProductOf3Maps (const EmbeddingMap< 1, 1 > & map_1, const EmbeddingMap< 1, 1 > & map_2, const EmbeddingMap< 1, 1 > & map_3)
ProductOf3Maps() [2/5]
EmbeddingMaps::ProductOf3Maps::ProductOf3Maps () default
~ProductOf3Maps()
EmbeddingMaps::ProductOf3Maps::~ProductOf3Maps () override default
ProductOf3Maps() [3/5]
EmbeddingMaps::ProductOf3Maps::ProductOf3Maps (const ProductOf3Maps & other)
ProductOf3Maps() [4/5]
EmbeddingMaps::ProductOf3Maps::ProductOf3Maps (ProductOf3Maps &&) noexcept
ProductOf3Maps() [5/5]
EmbeddingMaps::ProductOf3Maps::ProductOf3Maps (CkMigrateMessage *) explicit
Member Function Documentation
get_clone()
std::unique_ptr<EmbeddingMap<3, 3> > EmbeddingMaps::ProductOf3Maps::get_clone () const inline override virtual
Return a copy of the concrete EmbeddingMap.
Implements EmbeddingMap< 3, 3 >.
References EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::inv_jacobian(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::inverse(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::jacobian(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::operator()(), EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::pup(), and EmbeddingMaps::ProductOf2Maps< Dim1, Dim2 >::WRAPPED_PUPable_decl_base_template().
inv_jacobian()
double EmbeddingMaps::ProductOf3Maps::inv_jacobian (const Point< 3, Frame::Logical > & xi, size_t ud, size_t ld) const override
References ASSERT.
inverse()
Point< 3, Frame::Logical > EmbeddingMaps::ProductOf3Maps::inverse (const Point< 3, Frame::Grid > & x) const override
jacobian()
double EmbeddingMaps::ProductOf3Maps::jacobian (const Point< 3, Frame::Logical > & xi, size_t ud, size_t ld) const override
References ASSERT.
operator()()
Point< 3, Frame::Grid > EmbeddingMaps::ProductOf3Maps::operator() (const Point< 3, Frame::Logical > & xi) const override
operator=() [1/2]
ProductOf3Maps& EmbeddingMaps::ProductOf3Maps::operator= (const ProductOf3Maps &) delete
operator=() [2/2]
ProductOf3Maps& EmbeddingMaps::ProductOf3Maps::operator= (ProductOf3Maps &&) default
pup()
void EmbeddingMaps::ProductOf3Maps::pup (PUP::er & p) override
WRAPPED_PUPable_decl_base_template()
EmbeddingMaps::ProductOf3Maps::WRAPPED_PUPable_decl_base_template (SINGLE_ARG(EmbeddingMap< 3, 3 >) , ProductOf3Maps)
The documentation for this class was generated from the following files:
src/Domain/EmbeddingMaps/ProductMaps.hpp
src/Domain/EmbeddingMaps/ProductMaps.cpp