SpECTRE: CoordinateMaps::Rotation< 2 > Class Template Reference
CoordinateMaps::Rotation< 2 > Class Template Reference
Coordinate Maps
Spatial rotation in two dimensions.
#include <Rotation.hpp>
Public Member Functions
Rotation (double rotation_angle)
Constructor.
Rotation ()=default
~Rotation ()=default
Rotation (const Rotation &)=default
Rotation & operator= (const Rotation &)=default
Rotation (Rotation &&) noexcept=default
Rotation & operator= (Rotation &&)=default
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, 2 > operator() (const std::array< T, 2 > &xi) const
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, 2 > inverse (const std::array< T, 2 > &x) const
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 2, UpLo::Up, Frame::NoFrame >, SpatialIndex< 2, UpLo::Lo, Frame::NoFrame > > > jacobian (const std::array< T, 2 > &) const
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 2, UpLo::Up, Frame::NoFrame >, SpatialIndex< 2, UpLo::Lo, Frame::NoFrame > > > inv_jacobian (const std::array< T, 2 > &) const
void pup (PUP::er &p)
Static Public Attributes
static constexpr size_t dim = 2
Friends
bool operator== (const Rotation< 2 > &lhs, const Rotation< 2 > &rhs) noexcept
Detailed Description
template<>
class CoordinateMaps::Rotation< 2 >
Spatial rotation in two dimensions.
Let \((R,\Phi)\) be the polar coordinates associated with \((\xi,\eta)\). Let \((r,\phi)\) be the polar coordinates associated with \((x,y)\). Applies the spatial rotation \(\phi = \Phi + \alpha\).
The formula for the mapping is:
\begin{eqnarray*} x &=& \xi \cos \alpha - \eta \sin \alpha \\ y &=& \xi \sin \alpha + \eta \cos \alpha \end{eqnarray*}
.
Constructor & Destructor Documentation
Rotation() [1/4]
CoordinateMaps::Rotation< 2 >::Rotation (double rotation_angle) explicit
Constructor.
Parameters
rotation_angle the angle \(\alpha\) (in radians).
References operator()().
Rotation() [2/4]
CoordinateMaps::Rotation< 2 >::Rotation () default
~Rotation()
CoordinateMaps::Rotation< 2 >::~Rotation () default
Rotation() [3/4]
CoordinateMaps::Rotation< 2 >::Rotation (const Rotation< 2 > &) default
Rotation() [4/4]
CoordinateMaps::Rotation< 2 >::Rotation (Rotation< 2 > &&) default noexcept
Member Function Documentation
inv_jacobian()
template<typename T > template Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 2, UpLo::Up, Frame::NoFrame >, SpatialIndex< 2, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::Rotation< 2 >::inv_jacobian (const std::array< T, 2 > &) const
Referenced by CoordinateMaps::operator!=().
inverse()
template<typename T > template std::array< DataVector, 2 > CoordinateMaps::Rotation< 2 >::inverse (const std::array< T, 2 > & x) const
Referenced by CoordinateMaps::operator!=().
jacobian()
template<typename T > template Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 2, UpLo::Up, Frame::NoFrame >, SpatialIndex< 2, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::Rotation< 2 >::jacobian (const std::array< T, 2 > &) const
Referenced by CoordinateMaps::operator!=().
operator()()
template<typename T > template std::array< DataVector, 2 > CoordinateMaps::Rotation< 2 >::operator() (const std::array< T, 2 > & xi) const
Referenced by CoordinateMaps::operator!=(), and Rotation().
operator=() [1/2]
Rotation& CoordinateMaps::Rotation< 2 >::operator= (const Rotation< 2 > &) default
operator=() [2/2]
Rotation& CoordinateMaps::Rotation< 2 >::operator= (Rotation< 2 > &&) default
pup()
void CoordinateMaps::Rotation< 2 >::pup (PUP::er & p)
Friends And Related Function Documentation
operator==
bool operator== (const Rotation< 2 > & lhs, const Rotation< 2 > & rhs) friend
Member Data Documentation
dim
constexpr size_t CoordinateMaps::Rotation< 2 >::dim = 2 static
The documentation for this class was generated from the following files:
src/Domain/CoordinateMaps/Rotation.hpp
src/Domain/CoordinateMaps/Rotation.cpp