SpECTRE: CoordinateMaps::AffineMap Class Reference
CoordinateMaps::AffineMap Class Reference
Coordinate Maps
Linear map from \(\xi \in [A, B]\rightarrow x \in [a, b]\).
#include <AffineMap.hpp>
Public Member Functions
AffineMap (double A, double B, double a, double b)
AffineMap ()=default
~AffineMap ()=default
AffineMap (const AffineMap &)=default
AffineMap (AffineMap &&) noexcept=default
AffineMap & operator= (const AffineMap &)=default
AffineMap & operator= (AffineMap &&)=default
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, 1 > operator() (const std::array< T, 1 > &xi) const
template<typename T >
std::array< std::decay_t< tt::remove_reference_wrapper_t< T > >, 1 > inverse (const std::array< T, 1 > &x) const
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 1, UpLo::Up, Frame::NoFrame >, SpatialIndex< 1, UpLo::Lo, Frame::NoFrame > > > inv_jacobian (const std::array< T, 1 > &) const
template<typename T >
Tensor< std::decay_t< tt::remove_reference_wrapper_t< T > >, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 1, UpLo::Up, Frame::NoFrame >, SpatialIndex< 1, UpLo::Lo, Frame::NoFrame > > > jacobian (const std::array< T, 1 > &) const
void pup (PUP::er &p)
Static Public Attributes
static constexpr size_t dim = 1
Friends
bool operator== (const AffineMap &lhs, const AffineMap &rhs) noexcept
Detailed Description
Linear map from \(\xi \in [A, B]\rightarrow x \in [a, b]\).
The formula for the mapping is...
\[ x = \frac{b}{B-A} (\xi-A) +\frac{a}{B-A}(B-\xi) \]
\[ \xi =\frac{B}{b-a} (x-a) +\frac{A}{b-a}(b-x) \]
Constructor & Destructor Documentation
AffineMap() [1/4]
CoordinateMaps::AffineMap::AffineMap (double A, double B, double a, double b)
References operator()().
AffineMap() [2/4]
CoordinateMaps::AffineMap::AffineMap () default
~AffineMap()
CoordinateMaps::AffineMap::~AffineMap () default
AffineMap() [3/4]
CoordinateMaps::AffineMap::AffineMap (const AffineMap &) default
AffineMap() [4/4]
CoordinateMaps::AffineMap::AffineMap (AffineMap &&) default noexcept
Member Function Documentation
inv_jacobian()
template<typename T > template Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 1, UpLo::Up, Frame::NoFrame >, SpatialIndex< 1, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::AffineMap::inv_jacobian (const std::array< T, 1 > &) const
Referenced by CoordinateMaps::operator==().
inverse()
template<typename T > template std::array< DataVector, 1 > CoordinateMaps::AffineMap::inverse (const std::array< T, 1 > & x) const
Referenced by CoordinateMaps::operator==().
jacobian()
template<typename T > template Tensor< DataVector, tmpl::integral_list< std::int32_t, 2, 1 >, index_list< SpatialIndex< 1, UpLo::Up, Frame::NoFrame >, SpatialIndex< 1, UpLo::Lo, Frame::NoFrame > > > CoordinateMaps::AffineMap::jacobian (const std::array< T, 1 > &) const
Referenced by CoordinateMaps::operator==().
operator()()
template<typename T > template std::array< DataVector, 1 > CoordinateMaps::AffineMap::operator() (const std::array< T, 1 > & xi) const
Referenced by AffineMap(), and CoordinateMaps::operator==().
operator=() [1/2]
AffineMap& CoordinateMaps::AffineMap::operator= (const AffineMap &) default
operator=() [2/2]
AffineMap& CoordinateMaps::AffineMap::operator= (AffineMap &&) default
pup()
void CoordinateMaps::AffineMap::pup (PUP::er & p)
Friends And Related Function Documentation
operator==
bool operator== (const AffineMap & lhs, const AffineMap & rhs) friend
Member Data Documentation
dim
constexpr size_t CoordinateMaps::AffineMap::dim = 1 static
The documentation for this class was generated from the following files:
src/Domain/CoordinateMaps/AffineMap.hpp
src/Domain/CoordinateMaps/AffineMap.cpp