SpECTRE: BlockNeighbor< VolumeDim > Class Template Reference
BlockNeighbor< VolumeDim > Class Template Reference
Computational Domain
Information about the neighbor of a Block in a particular direction.
#include <BlockNeighbor.hpp>
Public Member Functions
BlockNeighbor ()=default
BlockNeighbor (size_t id, Orientation< VolumeDim > orientation)
Construct with the Id and orientation of the neighbor.
~BlockNeighbor ()=default
BlockNeighbor (const BlockNeighbor< VolumeDim > &neighbor)=default
BlockNeighbor (BlockNeighbor< VolumeDim > &&) noexcept=default
BlockNeighbor< VolumeDim > & operator= (const BlockNeighbor< VolumeDim > &rhs)=default
BlockNeighbor< VolumeDim > & operator= (BlockNeighbor< VolumeDim > &&) noexcept=default
size_t id () const noexcept
const Orientation< VolumeDim > & orientation () const noexcept
void pup (PUP::er &p)
Detailed Description
template<size_t VolumeDim>
class BlockNeighbor< VolumeDim >
Information about the neighbor of a Block in a particular direction.
Template Parameters
VolumeDim the volume dimension.
Constructor & Destructor Documentation
BlockNeighbor() [1/4]
template<size_t VolumeDim> BlockNeighbor< VolumeDim >::BlockNeighbor () default
BlockNeighbor() [2/4]
template<size_t VolumeDim> BlockNeighbor< VolumeDim >::BlockNeighbor (size_t id, Orientation< VolumeDim > orientation)
Construct with the Id and orientation of the neighbor.
Parameters
id the Id of the neighbor.
orientation the Orientation of the neighbor.
~BlockNeighbor()
template<size_t VolumeDim> BlockNeighbor< VolumeDim >::~BlockNeighbor () default
BlockNeighbor() [3/4]
template<size_t VolumeDim> BlockNeighbor< VolumeDim >::BlockNeighbor (const BlockNeighbor< VolumeDim > & neighbor) default
BlockNeighbor() [4/4]
template<size_t VolumeDim> BlockNeighbor< VolumeDim >::BlockNeighbor (BlockNeighbor< VolumeDim > &&) default noexcept
Member Function Documentation
id()
template<size_t VolumeDim> size_t BlockNeighbor< VolumeDim >::id () const inline noexcept
Referenced by operator<<().
operator=() [1/2]
template<size_t VolumeDim> BlockNeighbor<VolumeDim>& BlockNeighbor< VolumeDim >::operator= (const BlockNeighbor< VolumeDim > & rhs) default
operator=() [2/2]
template<size_t VolumeDim> BlockNeighbor<VolumeDim>& BlockNeighbor< VolumeDim >::operator= (BlockNeighbor< VolumeDim > &&) default noexcept
orientation()
template<size_t VolumeDim> const Orientation<VolumeDim>& BlockNeighbor< VolumeDim >::orientation () const inline noexcept
References operator!=(), operator<<(), operator==(), and BlockNeighbor< VolumeDim >::pup().
Referenced by operator<<().
pup()
template<size_t VolumeDim> void BlockNeighbor< VolumeDim >::pup (PUP::er & p)
Referenced by BlockNeighbor< VolumeDim >::orientation().
The documentation for this class was generated from the following files:
src/Domain/BlockNeighbor.hpp
src/Domain/BlockNeighbor.cpp