SpECTRE: Neighbors< VolumeDim > Class Template Reference
Neighbors< VolumeDim > Class Template Reference
Computational Domain
Information about the neighbors of an Element in a particular direction.
#include <Neighbors.hpp>
Public Member Functions
Neighbors (std::unordered_set< ElementId< VolumeDim >> ids, Orientation< VolumeDim > orientation)
Construct with the ids and orientation of the neighbors.
Neighbors ()=default
Default constructor for Charm++ serialization.
~Neighbors ()=default
Neighbors (const Neighbors< VolumeDim > &neighbor)=default
Neighbors (Neighbors< VolumeDim > &&) noexcept=default
Neighbors< VolumeDim > & operator= (const Neighbors< VolumeDim > &rhs)=default
Neighbors< VolumeDim > & operator= (Neighbors< VolumeDim > &&) noexcept
const std::unordered_set< ElementId< VolumeDim > > & ids () const noexcept
const Orientation< VolumeDim > & orientation () const noexcept
void set_ids_to (const std::unordered_set< ElementId< VolumeDim >> new_ids) noexcept
Reset the ids of the neighbors.
void add_ids (const std::unordered_set< ElementId< VolumeDim >> &additional_ids)
Add ids of neighbors. Adding an existing neighbor is allowed.
void pup (PUP::er &p)
Serialization for Charm++.
size_t size () const noexcept
The number of neighbors.
std::unordered_set< ElementId< VolumeDim > >::iterator begin ()
std::unordered_set< ElementId< VolumeDim > >::iterator end ()
std::unordered_set< ElementId< VolumeDim > >::const_iterator begin () const
std::unordered_set< ElementId< VolumeDim > >::const_iterator end () const
std::unordered_set< ElementId< VolumeDim > >::const_iterator cbegin () const
std::unordered_set< ElementId< VolumeDim > >::const_iterator cend () const
Detailed Description
template<size_t VolumeDim>
class Neighbors< VolumeDim >
Information about the neighbors of an Element in a particular direction.
Template Parameters
VolumeDim the volume dimension.
Constructor & Destructor Documentation
Neighbors() [1/4]
template<size_t VolumeDim> Neighbors< VolumeDim >::Neighbors (std::unordered_set< ElementId< VolumeDim >> ids, Orientation< VolumeDim > orientation)
Construct with the ids and orientation of the neighbors.
Parameters
ids the ids of the neighbors.
orientation the Orientation of the neighbors.
Neighbors() [2/4]
template<size_t VolumeDim> Neighbors< VolumeDim >::Neighbors () default
Default constructor for Charm++ serialization.
~Neighbors()
template<size_t VolumeDim> Neighbors< VolumeDim >::~Neighbors () default
Neighbors() [3/4]
template<size_t VolumeDim> Neighbors< VolumeDim >::Neighbors (const Neighbors< VolumeDim > & neighbor) default
Neighbors() [4/4]
template<size_t VolumeDim> Neighbors< VolumeDim >::Neighbors (Neighbors< VolumeDim > &&) default noexcept
Member Function Documentation
add_ids()
template<size_t VolumeDim> void Neighbors< VolumeDim >::add_ids (const std::unordered_set< ElementId< VolumeDim >> & additional_ids)
Add ids of neighbors. Adding an existing neighbor is allowed.
Referenced by Neighbors< VolumeDim >::set_ids_to(), and TEST_CASE().
begin() [1/2]
template<size_t VolumeDim> std::unordered_set<ElementId<VolumeDim> >::iterator Neighbors< VolumeDim >::begin () inline
begin() [2/2]
template<size_t VolumeDim> std::unordered_set<ElementId<VolumeDim> >::const_iterator Neighbors< VolumeDim >::begin () const inline
cbegin()
template<size_t VolumeDim> std::unordered_set<ElementId<VolumeDim> >::const_iterator Neighbors< VolumeDim >::cbegin () const inline
cend()
template<size_t VolumeDim> std::unordered_set<ElementId<VolumeDim> >::const_iterator Neighbors< VolumeDim >::cend () const inline
References operator!=(), and operator==().
end() [1/2]
template<size_t VolumeDim> std::unordered_set<ElementId<VolumeDim> >::iterator Neighbors< VolumeDim >::end () inline
end() [2/2]
template<size_t VolumeDim> std::unordered_set<ElementId<VolumeDim> >::const_iterator Neighbors< VolumeDim >::end () const inline
ids()
template<size_t VolumeDim> const std::unordered_set<ElementId<VolumeDim> >& Neighbors< VolumeDim >::ids () const inline noexcept
operator=() [1/2]
template<size_t VolumeDim> Neighbors<VolumeDim>& Neighbors< VolumeDim >::operator= (const Neighbors< VolumeDim > & rhs) default
operator=() [2/2]
template<size_t VolumeDim> Neighbors<VolumeDim>& Neighbors< VolumeDim >::operator= (Neighbors< VolumeDim > &&) noexcept
orientation()
template<size_t VolumeDim> const Orientation<VolumeDim>& Neighbors< VolumeDim >::orientation () const inline noexcept
pup()
template<size_t VolumeDim> void Neighbors< VolumeDim >::pup (PUP::er & p)
Serialization for Charm++.
References operator!=(), and operator==().
Referenced by Neighbors< VolumeDim >::set_ids_to().
set_ids_to()
template<size_t VolumeDim> void Neighbors< VolumeDim >::set_ids_to (const std::unordered_set< ElementId< VolumeDim >> new_ids) inline noexcept
Reset the ids of the neighbors.
References Neighbors< VolumeDim >::add_ids(), and Neighbors< VolumeDim >::pup().
Referenced by TEST_CASE().
size()
template<size_t VolumeDim> size_t Neighbors< VolumeDim >::size () const inline noexcept
The number of neighbors.
Referenced by TEST_CASE().
The documentation for this class was generated from the following files:
src/Domain/Neighbors.hpp
src/Domain/Neighbors.cpp