SpECTRE: Computational Domain
Computational Domain
The building blocks used to describe the computational domain.
Classes
class Block< Map >
A Block<VolumeDim> is a region of a VolumeDim-dimensional computational domain that defines the root node of a tree which is used to construct the Elements that cover a region of the computational domain.
class BlockNeighbor< VolumeDim >
Information about the neighbor of a Block in a particular direction.
class CoordinateMap< SourceFrame, TargetFrame, Maps >
A coordinate map or composition of coordinate maps.
class Direction< VolumeDim >
A particular Side along a particular coordinate Axis.
class ElementId< VolumeDim >
An ElementId uniquely labels a Element. It is constructed from the BlockId of the Block to which the Element belongs and the VolumeDim SegementIds that label the segments of the Block that the Element covers.
class Neighbors< VolumeDim >
Information about the neighbors of an Element in a particular direction.
class SegmentId
A SegmentId labels a segment of the interval [-1,1]. A SegmentId is used to (partially) identify an Element. The segment is the interval [-1 + 2*(N/D), -1 + 2*(N+1)/D] where N = index_ and D = 2 ^ refinement_level_.
Enumerations
enum Side { Side::Lower, Side::Upper }
A label for the side of a manifold.
Functions
template<typename SourceFrame , typename TargetFrame , typename... Maps>
constexpr CoordinateMap< SourceFrame, TargetFrame, Maps... > make_coordinate_map (Maps &&... maps)
Creates a CoordinateMap of maps...
template<size_t VolumeDim, typename... Maps>
tnsr::I< DataVector, VolumeDim, Frame::Grid > grid_coordinates (const Index< VolumeDim > &extents, const CoordinateMap< Frame::Logical, Frame::Grid, Maps... > &coordinate_map)
Compute the grid coordinates in an Element.
template<size_t VolumeDim, typename... Maps>
tnsr::I< DataVector, VolumeDim, Frame::Grid > interface_grid_coordinates (const Index< VolumeDim - 1 > &extents, const CoordinateMap< Frame::Logical, Frame::Grid, Maps... > &coordinate_map, const Direction< VolumeDim > &direction)
Compute the grid coordinates on a face of an Element.
Detailed Description
The building blocks used to describe the computational domain.
Description
The VolumeDim-dimensional computational Domain is constructed from a set of non-overlapping Blocks. Each Block is a distorted VolumeDim-dimensional hyperrcube Each codimension-1 boundary of a Block is either part of the external boundary of the computational domain, or is identical to a boundary of one other Block. Each Block is subdivided into one or more Elements that may be changed dynamically if AMR is enabled.
Enumeration Type Documentation
Side
enum Side strong
A label for the side of a manifold.
Lower and Upper are with respect to the logical coordinate whose axis is normal to the side, i.e. beyond the Upper (Lower) side, the logical coordinate is increasing (decreasing).
Enumerator
Lower
Upper
Function Documentation
grid_coordinates()
template<size_t VolumeDim, typename... Maps> tnsr::I<DataVector, VolumeDim, Frame::Grid> grid_coordinates (const Index< VolumeDim > & extents, const CoordinateMap< Frame::Logical, Frame::Grid, Maps... > & coordinate_map)
Compute the grid coordinates in an Element.
Returns: grid-frame vector holding coordinates
Remarks: assumes that the grid-points lies at the Legendre-Gauss-Lobatto points of the reference cell
Details
Computes the grid coordinates by applying the coordinate_map at the Legendre-Gauss-Lobatto points of the reference cell.
Example
  const Index<3> extents_3d(Index<3>(5, 3, 2));
  const CoordinateMaps::AffineMap x_map{-1.0, 1.0, -3.0, 7.0};
  const CoordinateMaps::AffineMap y_map{-1.0, 1.0, -13.0, 47.0};
  const CoordinateMaps::AffineMap z_map{-1.0, 1.0, -32.0, 74.0};
  const auto map_3d = make_coordinate_map<Frame::Logical, Frame::Grid>(
      affine_map_3d{x_map, y_map, z_map});
  const auto x_3d = grid_coordinates(extents_3d, map_3d);
References Basis::lgl::collocation_points(), and Index< Dim >::product().
interface_grid_coordinates()
template<size_t VolumeDim, typename... Maps> tnsr::I<DataVector, VolumeDim, Frame::Grid> interface_grid_coordinates (const Index< VolumeDim - 1 > & extents, const CoordinateMap< Frame::Logical, Frame::Grid, Maps... > & coordinate_map, const Direction< VolumeDim > & direction)
Compute the grid coordinates on a face of an Element.
Returns: grid-frame vector holding coordinates
Remarks: assumes that the grid-points lies at the Legendre-Gauss-Lobatto points of the reference cell of the face
Details
Computes the grid coordinates by applying the coordinate_map at the Legendre-Gauss-Lobatto points of the reference cell of the face lying in the given direction.
Example
  const Index<2> extents_3d_zbdry(Index<2>(5, 3));
  const auto x_3d_lb_zeta = interface_grid_coordinates(
      extents_3d_zbdry, map_3d, Direction<3>::lower_zeta());
References gsl::at(), Basis::lgl::collocation_points(), Direction< VolumeDim >::dimension(), Lower, Index< Dim >::product(), and Direction< VolumeDim >::side().
make_coordinate_map()
template<typename SourceFrame , typename TargetFrame , typename... Maps> constexpr CoordinateMap<SourceFrame, TargetFrame, Maps...> make_coordinate_map (Maps &&... maps)
Creates a CoordinateMap of maps...