SpECTRE: src/Numerical/Spectral/Linearize.cpp File Reference
Linearize.cpp File Reference
#include "Numerical/Spectral/Linearize.hpp"
#include <array>
#include "DataStructures/DataVector.hpp"
#include "DataStructures/Index.hpp"
#include "DataStructures/Matrix.hpp"
#include "DataStructures/StripeIterator.hpp"
#include "Numerical/Spectral/LegendreGaussLobatto.hpp"
#include "Utilities/Blas.hpp"
#include "Utilities/MakeArray.hpp"
Functions
template<size_t Dim>
DataVector linearize (const DataVector &u, const Index< Dim > &extents)
template DataVector linearize< 1 > (const DataVector &, const Index< 1 > &)
template DataVector linearize< 2 > (const DataVector &, const Index< 2 > &)
template DataVector linearize< 3 > (const DataVector &, const Index< 3 > &)
template<size_t Dim>
DataVector linearize (const DataVector &u, const Index< Dim > &extents, const size_t d)
template DataVector linearize< 1 > (const DataVector &, const Index< 1 > &, const size_t)
template DataVector linearize< 2 > (const DataVector &, const Index< 2 > &, const size_t)
template DataVector linearize< 3 > (const DataVector &, const Index< 3 > &, const size_t)
Function Documentation
linearize< 1 >() [1/2]
template DataVector linearize< 1 > (const DataVector & , const Index< 1 > &)
Referenced by linearize().
linearize< 1 >() [2/2]
template DataVector linearize< 1 > (const DataVector & , const Index< 1 > & , const size_t)
linearize< 2 >() [1/2]
template DataVector linearize< 2 > (const DataVector & , const Index< 2 > &)
Referenced by linearize().
linearize< 2 >() [2/2]
template DataVector linearize< 2 > (const DataVector & , const Index< 2 > & , const size_t)
linearize< 3 >() [1/2]
template DataVector linearize< 3 > (const DataVector & , const Index< 3 > &)
Referenced by linearize().
linearize< 3 >() [2/2]
template DataVector linearize< 3 > (const DataVector & , const Index< 3 > & , const size_t)