SpECTRE: gsl Namespace Reference
gsl Namespace Reference
Utilities
Implementations from the Guideline Support Library.
Classes
class not_null
Require a pointer to not be a nullptr
Functions
template<class T , class U >
constexpr T narrow_cast (U &&u) noexcept
Cast u to a type T where the cast may result in narrowing.
template<class T , class U >
T narrow (U u)
A checked version of narrow_cast() that ERRORs if the cast changed the value.
template<class T >
std::ostream & operator<< (std::ostream &os, const not_null< T > &val)
template<class T , class U >
auto operator== (const not_null< T > &lhs, const not_null< U > &rhs) -> decltype(lhs.get()==rhs.get())
template<class T , class U >
auto operator!= (const not_null< T > &lhs, const not_null< U > &rhs) -> decltype(lhs.get() !=rhs.get())
template<class T , class U >
auto operator< (const not_null< T > &lhs, const not_null< U > &rhs) -> decltype(lhs.get()< rhs.get())
template<class T , class U >
auto operator<= (const not_null< T > &lhs, const not_null< U > &rhs) -> decltype(lhs.get()<=rhs.get())
template<class T , class U >
auto operator> (const not_null< T > &lhs, const not_null< U > &rhs) -> decltype(lhs.get() > rhs.get())
template<class T , class U >
auto operator>= (const not_null< T > &lhs, const not_null< U > &rhs) -> decltype(lhs.get() >=rhs.get())
template<class T , class U >
std::ptrdiff_t operator- (const not_null< T > &, const not_null< U > &)=delete
template<class T >
not_null< T > operator- (const not_null< T > &, std::ptrdiff_t)=delete
template<class T >
not_null< T > operator+ (const not_null< T > &, std::ptrdiff_t)=delete
template<class T >
not_null< T > operator+ (std::ptrdiff_t, const not_null< T > &)=delete
template<class T , std::size_t N, typename Size >
constexpr T & at (std::array< T, N > &arr, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
template<class Cont , typename Size >
constexpr const Cont::value_type & at (const Cont &cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
template<class T , typename Size >
constexpr const T & at (std::initializer_list< T > cont, Size index)
Retrieve a entry from a container, with checks in Debug mode that the index being retrieved is valid.
Detailed Description
Implementations from the Guideline Support Library.
Function Documentation
operator!=()
template<class T , class U > auto gsl::operator!= (const not_null< T > & lhs, const not_null< U > & rhs) -> decltype(lhs.get() != rhs.get())
operator+() [1/2]
template<class T > not_null<T> gsl::operator+ (const not_null< T > & , std::ptrdiff_t) delete
Referenced by operator>=().
operator+() [2/2]
template<class T > not_null<T> gsl::operator+ (std::ptrdiff_t , const not_null< T > &) delete
operator-() [1/2]
template<class T , class U > std::ptrdiff_t gsl::operator- (const not_null< T > & , const not_null< U > &) delete
Referenced by operator>=().
operator-() [2/2]
template<class T > not_null<T> gsl::operator- (const not_null< T > & , std::ptrdiff_t) delete
operator<()
template<class T , class U > auto gsl::operator< (const not_null< T > & lhs, const not_null< U > & rhs) -> decltype(lhs.get() < rhs.get())
References gsl::not_null< T >::get().
operator<<()
template<class T > std::ostream& gsl::operator<< (std::ostream & os, const not_null< T > & val)
operator<=()
template<class T , class U > auto gsl::operator<= (const not_null< T > & lhs, const not_null< U > & rhs) -> decltype(lhs.get() <= rhs.get())
References gsl::not_null< T >::get().
operator==()
template<class T , class U > auto gsl::operator== (const not_null< T > & lhs, const not_null< U > & rhs) -> decltype(lhs.get() == rhs.get())
operator>()
template<class T , class U > auto gsl::operator> (const not_null< T > & lhs, const not_null< U > & rhs) -> decltype(lhs.get() > rhs.get())
operator>=()
template<class T , class U > auto gsl::operator>= (const not_null< T > & lhs, const not_null< U > & rhs) -> decltype(lhs.get() >= rhs.get())
References operator+(), and operator-().