SpECTRE: CoordinateMaps Namespace Reference
CoordinateMaps Namespace Reference
Contains all embedding maps.
Classes
class AffineMap
Linear map from \(\xi \in [A, B]\rightarrow x \in [a, b]\).
class Identity
Identity map from \(\xi \rightarrow x\).
class ProductOf2Maps
Product of two codimension=0 CoordinateMaps.
class ProductOf3Maps
Product of three one-dimensional CoordinateMaps.
class Rotation< 2 >
Spatial rotation in two dimensions.
class Rotation< 3 >
Spatial rotation in three dimensions using Euler angles.
Functions
bool operator== (const CoordinateMaps::AffineMap &lhs, const CoordinateMaps::AffineMap &rhs) noexcept
bool operator!= (const CoordinateMaps::AffineMap &lhs, const CoordinateMaps::AffineMap &rhs) noexcept
template<size_t Dim>
constexpr bool operator== (const CoordinateMaps::Identity< Dim > &, const CoordinateMaps::Identity< Dim > &) noexcept
template<size_t Dim>
constexpr bool operator!= (const CoordinateMaps::Identity< Dim > &lhs, const CoordinateMaps::Identity< Dim > &rhs) noexcept
template<typename Map1 , typename Map2 >
bool operator!= (const ProductOf2Maps< Map1, Map2 > &lhs, const ProductOf2Maps< Map1, Map2 > &rhs) noexcept
template<typename Map1 , typename Map2 , typename Map3 >
bool operator!= (const ProductOf3Maps< Map1, Map2, Map3 > &lhs, const ProductOf3Maps< Map1, Map2, Map3 > &rhs) noexcept
bool operator== (const Rotation< 2 > &lhs, const Rotation< 2 > &rhs) noexcept
bool operator!= (const Rotation< 2 > &lhs, const Rotation< 2 > &rhs) noexcept
bool operator== (const Rotation< 3 > &lhs, const Rotation< 3 > &rhs) noexcept
bool operator!= (const Rotation< 3 > &lhs, const Rotation< 3 > &rhs) noexcept
Variables
template<typename FirstMap , typename... Maps>
constexpr size_t map_dim = FirstMap::dim
Detailed Description
Contains all embedding maps.
Function Documentation
operator!=() [1/6]
template<size_t Dim> constexpr bool CoordinateMaps::operator!= (const CoordinateMaps::Identity< Dim > & lhs, const CoordinateMaps::Identity< Dim > & rhs) inline noexcept
operator!=() [2/6]
bool CoordinateMaps::operator!= (const CoordinateMaps::AffineMap & lhs, const CoordinateMaps::AffineMap & rhs) inline noexcept
operator!=() [3/6]
bool CoordinateMaps::operator!= (const Rotation< 2 > & lhs, const Rotation< 2 > & rhs) noexcept
operator!=() [4/6]
template<typename Map1 , typename Map2 > bool CoordinateMaps::operator!= (const ProductOf2Maps< Map1, Map2 > & lhs, const ProductOf2Maps< Map1, Map2 > & rhs) noexcept
operator!=() [5/6]
bool CoordinateMaps::operator!= (const Rotation< 3 > & lhs, const Rotation< 3 > & rhs) noexcept
References CoordinateMaps::Rotation< 2 >::inv_jacobian(), CoordinateMaps::Rotation< 3 >::inv_jacobian(), CoordinateMaps::Rotation< 2 >::inverse(), CoordinateMaps::Rotation< 3 >::inverse(), CoordinateMaps::Rotation< 2 >::jacobian(), CoordinateMaps::Rotation< 3 >::jacobian(), CoordinateMaps::Rotation< 2 >::operator()(), and CoordinateMaps::Rotation< 3 >::operator()().
operator!=() [6/6]
template<typename Map1 , typename Map2 , typename Map3 > bool CoordinateMaps::operator!= (const ProductOf3Maps< Map1, Map2, Map3 > & lhs, const ProductOf3Maps< Map1, Map2, Map3 > & rhs) noexcept
operator==() [1/4]
template<size_t Dim> constexpr bool CoordinateMaps::operator== (const CoordinateMaps::Identity< Dim > & , const CoordinateMaps::Identity< Dim > &) inline noexcept
operator==() [2/4]
bool CoordinateMaps::operator== (const CoordinateMaps::AffineMap & lhs, const CoordinateMaps::AffineMap & rhs) noexcept
References CoordinateMaps::AffineMap::inv_jacobian(), CoordinateMaps::AffineMap::inverse(), CoordinateMaps::AffineMap::jacobian(), and CoordinateMaps::AffineMap::operator()().
operator==() [3/4]
bool CoordinateMaps::operator== (const Rotation< 2 > & lhs, const Rotation< 2 > & rhs) noexcept
operator==() [4/4]
bool CoordinateMaps::operator== (const Rotation< 3 > & lhs, const Rotation< 3 > & rhs) noexcept
Variable Documentation
map_dim
template<typename FirstMap , typename... Maps> constexpr size_t CoordinateMaps::map_dim = FirstMap::dim