SpECTRE: src/Domain/Neighbors.cpp File Reference
Neighbors.cpp File Reference
#include "Domain/Neighbors.hpp"
#include <charm.h>
#include <ostream>
#include "Domain/ElementId.hpp"
#include "Parallel/PupStlCpp11.hpp"
#include "Utilities/StdHelpers.hpp"
Functions
template<size_t VolumeDim>
std::ostream & operator<< (std::ostream &os, const Neighbors< VolumeDim > &n)
Output operator for Neighborss.
template<size_t VolumeDim>
bool operator== (const Neighbors< VolumeDim > &lhs, const Neighbors< VolumeDim > &rhs) noexcept
template<size_t VolumeDim>
bool operator!= (const Neighbors< VolumeDim > &lhs, const Neighbors< VolumeDim > &rhs) noexcept
template std::ostream & operator<< (std::ostream &, const Neighbors< 1 > &)
template std::ostream & operator<< (std::ostream &, const Neighbors< 2 > &)
template std::ostream & operator<< (std::ostream &, const Neighbors< 3 > &)
template bool operator== (const Neighbors< 1 > &, const Neighbors< 1 > &)
template bool operator== (const Neighbors< 2 > &, const Neighbors< 2 > &)
template bool operator== (const Neighbors< 3 > &, const Neighbors< 3 > &)
template bool operator!= (const Neighbors< 1 > &, const Neighbors< 1 > &)
template bool operator!= (const Neighbors< 2 > &, const Neighbors< 2 > &)
template bool operator!= (const Neighbors< 3 > &, const Neighbors< 3 > &)
Function Documentation
operator!=() [1/4]
template<size_t VolumeDim> bool operator!= (const Neighbors< VolumeDim > & lhs, const Neighbors< VolumeDim > & rhs) noexcept
Referenced by Neighbors< VolumeDim >::cend(), and Neighbors< VolumeDim >::pup().
operator!=() [2/4]
template bool operator!= (const Neighbors< 1 > & , const Neighbors< 1 > &)
operator!=() [3/4]
template bool operator!= (const Neighbors< 2 > & , const Neighbors< 2 > &)
operator!=() [4/4]
template bool operator!= (const Neighbors< 3 > & , const Neighbors< 3 > &)
operator<<() [1/4]
template<size_t VolumeDim> std::ostream& operator<< (std::ostream & os, const Neighbors< VolumeDim > & n)
Output operator for Neighborss.
operator<<() [2/4]
template std::ostream& operator<< (std::ostream & , const Neighbors< 1 > &)
operator<<() [3/4]
template std::ostream& operator<< (std::ostream & , const Neighbors< 2 > &)
operator<<() [4/4]
template std::ostream& operator<< (std::ostream & , const Neighbors< 3 > &)
operator==() [1/4]
template<size_t VolumeDim> bool operator== (const Neighbors< VolumeDim > & lhs, const Neighbors< VolumeDim > & rhs) noexcept
Referenced by Neighbors< VolumeDim >::cend(), and Neighbors< VolumeDim >::pup().
operator==() [2/4]
template bool operator== (const Neighbors< 1 > & , const Neighbors< 1 > &)
operator==() [3/4]
template bool operator== (const Neighbors< 2 > & , const Neighbors< 2 > &)
operator==() [4/4]
template bool operator== (const Neighbors< 3 > & , const Neighbors< 3 > &)