SpECTRE: src/Time/Slab.hpp File Reference
Slab.hpp File Reference
Defines class Slab.
#include <functional>
#include <limits>
#include "ErrorHandling/Assert.hpp"
Classes
class Slab
A chunk of time. Every element must reach slab boundaries exactly, no matter how it actually takes time steps to get there. The simulation can only be assumed to have global data available at slab boundaries.
Functions
bool operator== (const Slab &a, const Slab &b) noexcept
bool operator!= (const Slab &a, const Slab &b) noexcept
std::ostream & operator<< (std::ostream &os, const Slab &s) noexcept
size_t hash_value (const Slab &s) noexcept
bool operator< (const Slab &a, const Slab &b) noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
bool operator> (const Slab &a, const Slab &b) noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
bool operator<= (const Slab &a, const Slab &b) noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
bool operator>= (const Slab &a, const Slab &b) noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
Detailed Description
Defines class Slab.
Function Documentation
hash_value()
size_t hash_value (const Slab & s) noexcept
Referenced by operator>=().
operator!=()
bool operator!= (const Slab & a, const Slab & b) inline noexcept
operator<()
bool operator< (const Slab & a, const Slab & b) inline noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
References ASSERT.
operator<<()
std::ostream& operator<< (std::ostream & os, const Slab & s) noexcept
Referenced by operator>=().
operator<=()
bool operator<= (const Slab & a, const Slab & b) inline noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
operator==()
bool operator== (const Slab & a, const Slab & b) inline noexcept
operator>()
bool operator> (const Slab & a, const Slab & b) inline noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
operator>=()
bool operator>= (const Slab & a, const Slab & b) inline noexcept
Slab comparison operators give the time ordering. Overlapping unequal slabs should not be compared (and will trigger an assertion).
References hash_value(), and operator<<().