SpECTRE: src/Utilities/StdHelpers.hpp File Reference
StdHelpers.hpp File Reference
Defines helper functions for the standard library.
#include <algorithm>
#include <array>
#include <chrono>
#include <ctime>
#include <deque>
#include <future>
#include <iterator>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include "Utilities/Gsl.hpp"
#include "Utilities/Requires.hpp"
#include "Utilities/StlStreamDeclarations.hpp"
#include "Utilities/TypeTraits.hpp"
Functions
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::list< T > &v)
Output the items of a std::list.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::vector< T > &v)
Output the items of a std::vector.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::deque< T > &v)
Output the items of a std::deque.
template<typename T , size_t N>
std::ostream & operator<< (std::ostream &os, const std::array< T, N > &a)
Output the items of a std::array.
template<typename... Args>
std::ostream & operator<< (std::ostream &os, const std::tuple< Args... > &t)
Stream operator for tuples.
template<typename K , typename V >
std::ostream & operator<< (std::ostream &os, const std::unordered_map< K, V > &m)
Output all the key, value pairs of a std::unordered_map.
template<typename K , typename V , typename C >
std::ostream & operator<< (std::ostream &os, const std::map< K, V, C > &m)
Output all the key, value pairs of a std::map.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::unordered_set< T > &v)
Output the items of a std::unordered_set.
template<typename T , typename C >
std::ostream & operator<< (std::ostream &os, const std::set< T, C > &v)
Output the items of a std::set.
template<typename T , Requires< tt::is_streamable< std::ostream, T >::value > >
std::ostream & operator<< (std::ostream &os, const std::unique_ptr< T > &t)
Stream operator for std::unique_ptr.
template<typename T , Requires< tt::is_streamable< std::ostream, T >::value > >
std::ostream & operator<< (std::ostream &os, const std::shared_ptr< T > &t)
Stream operator for std::shared_ptr.
template<typename T , typename U >
std::ostream & operator<< (std::ostream &os, const std::pair< T, U > &t)
Stream operator for std::pair.
template<typename K , typename V >
std::string keys_of (const std::unordered_map< K, V > &m)
Construct a string containing the keys of a std::unordered_map.
template<typename K , typename V , typename C >
std::string keys_of (const std::map< K, V, C > &m)
Construct a string containing the keys of a std::map.
template<typename... Args>
std::string formatted_string (const std::string &fmt, Args... args)
Format a string like printf.
template<size_t Dim, typename T >
std::array< T, Dim > & operator+= (std::array< T, Dim > &lhs, const std::array< T, Dim > &rhs) noexcept(noexcept(lhs[0]+=rhs[0]))
template<size_t Dim, typename T >
std::array< T, Dim > operator+ (const std::array< T, Dim > &lhs, const std::array< T, Dim > &rhs) noexcept(noexcept(std::declval< std::array< T, Dim > &>()+=rhs) and noexcept(std::array< T, Dim >{lhs}))
template<size_t Dim, typename T >
std::array< T, Dim > & operator-= (std::array< T, Dim > &lhs, const std::array< T, Dim > &rhs) noexcept(noexcept(lhs[0] -=rhs[0]))
template<size_t Dim, typename T >
std::array< T, Dim > operator- (const std::array< T, Dim > &lhs, const std::array< T, Dim > &rhs) noexcept(noexcept(std::declval< std::array< T, Dim > &>() -=rhs) and noexcept(std::array< T, Dim >{lhs}))
template<size_t Dim, typename T , typename U >
std::array< T, Dim > operator* (const std::array< T, Dim > &lhs, const U &scale) noexcept(noexcept(lhs[0] *scale) and noexcept(std::array< T, Dim >{}))
template<size_t Dim, typename T , typename U >
std::array< T, Dim > operator* (const U &scale, const std::array< T, Dim > &rhs) noexcept(noexcept(rhs *scale))
template<size_t Dim, typename T , typename U >
std::array< T, Dim > operator/ (const std::array< T, Dim > &lhs, const U &scale) noexcept(noexcept(lhs[0]/scale) and noexcept(std::array< T, Dim >{}))
template<size_t Dim, typename T >
std::array< T, Dim > operator- (const std::array< T, Dim > &rhs) noexcept(noexcept(-rhs[0]) and noexcept(std::array< T, Dim >{}))
Detailed Description
Defines helper functions for the standard library.
Function Documentation
operator*() [1/2]
template<size_t Dim, typename T , typename U > std::array<T, Dim> operator* (const std::array< T, Dim > & lhs, const U & scale) inline noexcept
References gsl::at().
operator*() [2/2]
template<size_t Dim, typename T , typename U > std::array<T, Dim> operator* (const U & scale, const std::array< T, Dim > & rhs) inline noexcept
operator+()
template<size_t Dim, typename T > std::array<T, Dim> operator+ (const std::array< T, Dim > & lhs, const std::array< T, Dim > & rhs) inline noexcept
operator+=()
template<size_t Dim, typename T > std::array<T, Dim>& operator+= (std::array< T, Dim > & lhs, const std::array< T, Dim > & rhs) inline noexcept
References gsl::at().
Referenced by Time::fraction(), TimeDelta::is_positive(), and gsl::not_null< T >::operator*().
operator-() [1/2]
template<size_t Dim, typename T > std::array<T, Dim> operator- (const std::array< T, Dim > & lhs, const std::array< T, Dim > & rhs) inline noexcept
operator-() [2/2]
template<size_t Dim, typename T > std::array<T, Dim> operator- (const std::array< T, Dim > & rhs) inline noexcept
References gsl::at().
operator-=()
template<size_t Dim, typename T > std::array<T, Dim>& operator-= (std::array< T, Dim > & lhs, const std::array< T, Dim > & rhs) inline noexcept
References gsl::at().
Referenced by Time::fraction(), TimeDelta::is_positive(), and gsl::not_null< T >::operator*().
operator/()
template<size_t Dim, typename T , typename U > std::array<T, Dim> operator/ (const std::array< T, Dim > & lhs, const U & scale) inline noexcept
References gsl::at().