SpECTRE: tests/Unit/Domain/Test_Block.cpp File Reference
Test_Block.cpp File Reference
#include <catch.hpp>
#include "Domain/Block.cpp"
#include "Domain/EmbeddingMaps/Identity.hpp"
#include "tests/Unit/TestHelpers.hpp"
Functions
template<size_t Dim>
void test_block ()
TEST_CASE ("Unit.Domain.Block.Identity", "[Domain][Unit]")
TEST_CASE ("Unit.Domain.Block.Neighbors", "[Domain][Unit]")
Function Documentation
test_block()
template<size_t Dim> void test_block ()
References test_move_semantics().
TEST_CASE() [1/2]
TEST_CASE ("Unit.Domain.Block.Identity" , "" [Domain][Unit])
TEST_CASE() [2/2]
TEST_CASE ("Unit.Domain.Block.Neighbors" , "" [Domain][Unit])
References Block< VolumeDim >::external_boundaries(), get_output(), Block< VolumeDim >::id(), Direction< VolumeDim >::lower_eta(), Direction< VolumeDim >::lower_xi(), Block< VolumeDim >::neighbors(), Direction< VolumeDim >::upper_eta(), and Direction< VolumeDim >::upper_xi().