SpECTRE: tests/Unit/Domain/Test_Neighbors.cpp File Reference
Test_Neighbors.cpp File Reference
#include <catch.hpp>
#include "Domain/Neighbors.hpp"
#include "tests/Unit/TestHelpers.hpp"
Functions
TEST_CASE ("Unit.Domain.Neighbors.1d", "[Domain][Unit]")
TEST_CASE ("Unit.Domain.Neighbors.2d", "[Domain][Unit]")
TEST_CASE ("Unit.Domain.Neighbors.3d", "[Domain][Unit]")
Function Documentation
TEST_CASE() [1/3]
TEST_CASE ("Unit.Domain.Neighbors.1d" , "" [Domain][Unit])
References Neighbors< VolumeDim >::add_ids(), Direction< VolumeDim >::lower_xi(), serialize_and_deserialize(), Neighbors< VolumeDim >::set_ids_to(), Neighbors< VolumeDim >::size(), and test_iterators().
TEST_CASE() [2/3]
TEST_CASE ("Unit.Domain.Neighbors.2d" , "" [Domain][Unit])
References Neighbors< VolumeDim >::add_ids(), Direction< VolumeDim >::lower_xi(), serialize_and_deserialize(), Neighbors< VolumeDim >::set_ids_to(), Neighbors< VolumeDim >::size(), test_copy_semantics(), test_iterators(), test_move_semantics(), and Direction< VolumeDim >::upper_eta().
TEST_CASE() [3/3]
TEST_CASE ("Unit.Domain.Neighbors.3d" , "" [Domain][Unit])
References Neighbors< VolumeDim >::add_ids(), serialize_and_deserialize(), Neighbors< VolumeDim >::set_ids_to(), Neighbors< VolumeDim >::size(), test_copy_semantics(), test_iterators(), test_move_semantics(), Direction< VolumeDim >::upper_eta(), Direction< VolumeDim >::upper_xi(), and Direction< VolumeDim >::upper_zeta().