SpECTRE: tests/Unit/Domain/Test_EmbeddingMaps.cpp File Reference
Test_EmbeddingMaps.cpp File Reference
#include <catch.hpp>
#include <random>
#include "DataStructures/Tensor/Tensor.hpp"
#include "Domain/EmbeddingMaps/AffineMap.hpp"
#include "Domain/EmbeddingMaps/Identity.hpp"
#include "Domain/EmbeddingMaps/ProductMaps.hpp"
#include "Domain/EmbeddingMaps/Rotation.hpp"
#include "Utilities/ConstantExpressions.hpp"
#include "tests/Unit/TestHelpers.hpp"
Functions
void test_rotation_3 (const EmbeddingMaps::Rotation< 3 > &three_dim_rotation_map, const Point< 3, Frame::Grid > &xi_hat, const Point< 3, Frame::Grid > &eta_hat, const Point< 3, Frame::Grid > &zeta_hat)
template<size_t Dim>
void test_identity ()
Function Documentation
test_identity()
template<size_t Dim> void test_identity ()
References EmbeddingMaps::Identity< Dim >::get_clone(), EmbeddingMaps::Identity< Dim >::inv_jacobian(), EmbeddingMaps::Identity< Dim >::inverse(), and EmbeddingMaps::Identity< Dim >::jacobian().
test_rotation_3()
void test_rotation_3 (const EmbeddingMaps::Rotation< 3 > & three_dim_rotation_map, const Point< 3, Frame::Grid > & xi_hat, const Point< 3, Frame::Grid > & eta_hat, const Point< 3, Frame::Grid > & zeta_hat)
References EmbeddingMaps::Rotation< 3 >::get_clone(), EmbeddingMaps::Rotation< 3 >::inv_jacobian(), EmbeddingMaps::Rotation< 3 >::inverse(), and EmbeddingMaps::Rotation< 3 >::jacobian().