SpECTRE: src/Time/Time.hpp File Reference
Time.hpp File Reference
Defines Time and TimeDelta.
#include <boost/rational.hpp>
#include <iosfwd>
#include "ErrorHandling/Assert.hpp"
#include "Time/Slab.hpp"
Classes
class Time
The time in a simulation. Times can be safely compared for exact equality as long as they do not belong to overlapping unequal slabs.
class TimeDelta
Represents an interval of time within a single slab.
Functions
bool operator== (const Time &a, const Time &b) noexcept
bool operator!= (const Time &a, const Time &b) noexcept
bool operator< (const Time &a, const Time &b) noexcept
bool operator> (const Time &a, const Time &b) noexcept
bool operator<= (const Time &a, const Time &b) noexcept
bool operator>= (const Time &a, const Time &b) noexcept
bool operator== (const TimeDelta &a, const TimeDelta &b) noexcept
bool operator!= (const TimeDelta &a, const TimeDelta &b) noexcept
bool operator< (const TimeDelta &a, const TimeDelta &b) noexcept
bool operator> (const TimeDelta &a, const TimeDelta &b) noexcept
bool operator<= (const TimeDelta &a, const TimeDelta &b) noexcept
bool operator>= (const TimeDelta &a, const TimeDelta &b) noexcept
TimeDelta operator- (const Time &a, const Time &b) noexcept
Time operator+ (Time a, const TimeDelta &b) noexcept
Time operator+ (const TimeDelta &a, Time b) noexcept
Time operator- (Time a, const TimeDelta &b) noexcept
TimeDelta operator+ (TimeDelta a, const TimeDelta &b) noexcept
TimeDelta operator- (TimeDelta a, const TimeDelta &b) noexcept
double operator/ (const TimeDelta &a, const TimeDelta &b) noexcept
TimeDelta operator* (TimeDelta a, const TimeDelta::rational_t &b) noexcept
TimeDelta operator* (const TimeDelta::rational_t &a, TimeDelta b) noexcept
TimeDelta operator/ (TimeDelta a, const TimeDelta::rational_t &b) noexcept
std::ostream & operator<< (std::ostream &os, const Time &t) noexcept
std::ostream & operator<< (std::ostream &os, const TimeDelta &dt) noexcept
size_t hash_value (const Time &t) noexcept
Detailed Description
Defines Time and TimeDelta.
Function Documentation
hash_value()
size_t hash_value (const Time & t) noexcept
Referenced by TimeDelta::operator/=().
operator!=() [1/2]
bool operator!= (const Time & a, const Time & b) inline noexcept
operator!=() [2/2]
bool operator!= (const TimeDelta & a, const TimeDelta & b) inline noexcept
operator*() [1/2]
TimeDelta operator* (TimeDelta a, const TimeDelta::rational_t & b) inline noexcept
operator*() [2/2]
TimeDelta operator* (const TimeDelta::rational_t & a, TimeDelta b) inline noexcept
operator+() [1/3]
Time operator+ (Time a, const TimeDelta & b) inline noexcept
Referenced by TimeDelta::is_positive().
operator+() [2/3]
Time operator+ (const TimeDelta & a, Time b) inline noexcept
operator+() [3/3]
TimeDelta operator+ (TimeDelta a, const TimeDelta & b) inline noexcept
operator-() [1/3]
TimeDelta operator- (const Time & a, const Time & b) noexcept
References ASSERT, and Time::TimeDelta.
Referenced by TimeDelta::is_positive(), and operator>=().
operator-() [2/3]
Time operator- (Time a, const TimeDelta & b) inline noexcept
operator-() [3/3]
TimeDelta operator- (TimeDelta a, const TimeDelta & b) inline noexcept
References operator/().
operator/() [1/2]
double operator/ (const TimeDelta & a, const TimeDelta & b) noexcept
Referenced by operator-().
operator/() [2/2]
TimeDelta operator/ (TimeDelta a, const TimeDelta::rational_t & b) inline noexcept
References operator<<().
operator<() [1/2]
bool operator< (const Time & a, const Time & b) inline noexcept
operator<() [2/2]
bool operator< (const TimeDelta & a, const TimeDelta & b) inline noexcept
References ASSERT.
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const Time & t) noexcept
Referenced by operator/().
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const TimeDelta & dt) noexcept
operator<=() [1/2]
bool operator<= (const Time & a, const Time & b) inline noexcept
operator<=() [2/2]
bool operator<= (const TimeDelta & a, const TimeDelta & b) inline noexcept
operator==() [1/2]
bool operator== (const Time & a, const Time & b) noexcept
operator==() [2/2]
bool operator== (const TimeDelta & a, const TimeDelta & b) inline noexcept
operator>() [1/2]
bool operator> (const Time & a, const Time & b) inline noexcept
operator>() [2/2]
bool operator> (const TimeDelta & a, const TimeDelta & b) inline noexcept
operator>=() [1/2]
bool operator>= (const Time & a, const Time & b) inline noexcept
operator>=() [2/2]
bool operator>= (const TimeDelta & a, const TimeDelta & b) inline noexcept
References operator-().