SpECTRE: tests/Unit/Time/TimeSteppers/TimeStepperTestUtils.hpp File Reference
TimeStepperTestUtils.hpp File Reference
#include <catch.hpp>
#include <cmath>
#include <deque>
#include <tuple>
#include "ErrorHandling/Assert.hpp"
#include "Time/Slab.hpp"
#include "Time/Time.hpp"
#include "Utilities/ConstantExpressions.hpp"
Functions
template<typename Stepper , typename F >
void take_step (Time &time, double &y, std::deque< std::tuple< Time, double, double >> &history, const Stepper &stepper, F &&rhs, const TimeDelta &step_size) noexcept
template<typename Stepper , typename F1 , typename F2 >
void initialize_history (Time time, std::deque< std::tuple< Time, double, double >> &history, const Stepper &stepper, F1 &&analytic, F2 &&rhs, TimeDelta step_size) noexcept
template<typename Stepper >
void check_multistep_properties (const Stepper &stepper) noexcept
template<typename Stepper >
void check_substep_properties (const Stepper &stepper) noexcept
template<typename Stepper >
void integrate_test (const Stepper &stepper, const double integration_time, const double epsilon) noexcept
template<typename Stepper >
void integrate_variable_test (const Stepper &stepper, const double epsilon) noexcept
template<typename Stepper >
void stability_test (const Stepper &stepper) noexcept
Function Documentation
check_multistep_properties()
template<typename Stepper > void check_multistep_properties (const Stepper & stepper) noexcept
check_substep_properties()
template<typename Stepper > void check_substep_properties (const Stepper & stepper) noexcept
initialize_history()
template<typename Stepper , typename F1 , typename F2 > void initialize_history (Time time, std::deque< std::tuple< Time, double, double >> & history, const Stepper & stepper, F1 && analytic, F2 && rhs, TimeDelta step_size) noexcept
References ASSERT.
Referenced by integrate_test(), integrate_variable_test(), and stability_test().
integrate_test()
template<typename Stepper > void integrate_test (const Stepper & stepper, const double integration_time, const double epsilon) noexcept
References approx, Slab::duration(), Slab::end(), initialize_history(), square(), Slab::start(), take_step(), Time::value(), Slab::with_duration_from_start(), and Slab::with_duration_to_end().
integrate_variable_test()
template<typename Stepper > void integrate_variable_test (const Stepper & stepper, const double epsilon) noexcept
References Slab::advance(), approx, Slab::duration(), Slab::end(), initialize_history(), square(), take_step(), Time::value(), Slab::with_duration_from_start(), and Slab::with_duration_to_end().
stability_test()
template<typename Stepper > void stability_test (const Stepper & stepper) noexcept
References Slab::duration(), initialize_history(), Slab::start(), take_step(), and Slab::with_duration_from_start().
take_step()
template<typename Stepper , typename F > void take_step (Time & time, double & y, std::deque< std::tuple< Time, double, double >> & history, const Stepper & stepper, F && rhs, const TimeDelta & step_size) noexcept
Referenced by integrate_test(), integrate_variable_test(), and stability_test().