SpECTRE: src/Time/Time.cpp File Reference
Time.cpp File Reference
#include "Time/Time.hpp"
#include <boost/functional/hash.hpp>
#include <ostream>
#include <pup.h>
Functions
bool operator== (const Time &a, const Time &b) noexcept
TimeDelta operator- (const Time &a, const Time &b) noexcept
std::ostream & operator<< (std::ostream &os, const Time &t) noexcept
double operator/ (const TimeDelta &a, const TimeDelta &b) noexcept
std::ostream & operator<< (std::ostream &os, const TimeDelta &dt) noexcept
size_t hash_value (const Time &t) noexcept
Function Documentation
hash_value()
size_t hash_value (const Time & t) noexcept
Referenced by TimeDelta::operator/=().
operator-()
TimeDelta operator- (const Time & a, const Time & b) noexcept
References ASSERT, and Time::TimeDelta.
Referenced by TimeDelta::is_positive(), and operator>=().
operator/()
double operator/ (const TimeDelta & a, const TimeDelta & b) noexcept
Referenced by operator-().
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const Time & t) noexcept
Referenced by operator/().
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const TimeDelta & dt) noexcept
operator==()
bool operator== (const Time & a, const Time & b) noexcept